/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author eavila
 */
public class cobrar extends javax.swing.JFrame {

    /**
     * Creates new form cobrar
     */
    public cobrar() {
        initComponents();
        this.setLocationRelativeTo(null);
        cobrar.Saldo.setText(cobros.Total.getText());
        cobrar.montoCobrar.setText(cobros.Total.getText());
        entregado.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Saldo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btcobrar = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        B50000 = new javax.swing.JButton();
        B20000 = new javax.swing.JButton();
        B100000 = new javax.swing.JButton();
        B10000 = new javax.swing.JButton();
        jentregado = new javax.swing.JPanel();
        entregado = new javax.swing.JTextField();
        jmonto = new javax.swing.JPanel();
        montoCobrar = new javax.swing.JTextField();
        jcambio = new javax.swing.JPanel();
        cambio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Saldo.setEditable(false);
        Saldo.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Saldo.setText("0");
        Saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaldoActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel14.setText("Saldo:");

        btcobrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btcobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/business-color_money-coins_icon-icons.com_53446.png"))); // NOI18N
        btcobrar.setEnabled(false);
        btcobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcobrarActionPerformed(evt);
            }
        });

        bcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_icon-icons.com_73703.png"))); // NOI18N

        bsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_90894.png"))); // NOI18N

        B50000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/billetes/50mil.PNG"))); // NOI18N
        B50000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B50000ActionPerformed(evt);
            }
        });

        B20000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/billetes/20mil.PNG"))); // NOI18N
        B20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B20000ActionPerformed(evt);
            }
        });

        B100000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/billetes/100mil.PNG"))); // NOI18N
        B100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B100000ActionPerformed(evt);
            }
        });

        B10000.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/billetes/10mil.PNG"))); // NOI18N
        B10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B10000ActionPerformed(evt);
            }
        });

        jentregado.setBackground(new java.awt.Color(173, 216, 230));
        jentregado.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TOTAL ENTREGADO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), java.awt.Color.blue)); // NOI18N
        jentregado.setEnabled(false);
        jentregado.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        entregado.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        entregado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entregadoActionPerformed(evt);
            }
        });
        entregado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                entregadoKeyPressed(evt);
            }
        });

        jmonto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MONTO A COBRAR", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), java.awt.Color.blue)); // NOI18N
        jmonto.setEnabled(false);

        montoCobrar.setEditable(false);
        montoCobrar.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        montoCobrar.setText("0");
        montoCobrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoCobrarActionPerformed(evt);
            }
        });
        montoCobrar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                montoCobrarKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jmontoLayout = new javax.swing.GroupLayout(jmonto);
        jmonto.setLayout(jmontoLayout);
        jmontoLayout.setHorizontalGroup(
            jmontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(montoCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, 429, Short.MAX_VALUE)
                .addContainerGap())
        );
        jmontoLayout.setVerticalGroup(
            jmontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jmontoLayout.createSequentialGroup()
                .addComponent(montoCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jcambio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CAMBIO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Agency FB", 1, 18), java.awt.Color.blue)); // NOI18N
        jcambio.setEnabled(false);

        cambio.setEditable(false);
        cambio.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        cambio.setText("0");
        cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jcambioLayout = new javax.swing.GroupLayout(jcambio);
        jcambio.setLayout(jcambioLayout);
        jcambioLayout.setHorizontalGroup(
            jcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcambioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cambio)
                .addContainerGap())
        );
        jcambioLayout.setVerticalGroup(
            jcambioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jcambioLayout.createSequentialGroup()
                .addComponent(cambio, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jentregadoLayout = new javax.swing.GroupLayout(jentregado);
        jentregado.setLayout(jentregadoLayout);
        jentregadoLayout.setHorizontalGroup(
            jentregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jentregadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entregado, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jentregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jmonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jcambio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jentregadoLayout.setVerticalGroup(
            jentregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jentregadoLayout.createSequentialGroup()
                .addGroup(jentregadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(entregado, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jentregadoLayout.createSequentialGroup()
                        .addComponent(jmonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcambio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btcobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(bcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(B10000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGap(28, 28, 28)
                            .addComponent(B20000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(B50000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B100000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jentregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Saldo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B20000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B10000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B50000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(B100000, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jentregado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btcobrar)
                    .addComponent(bcancelar)
                    .addComponent(bsalir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaldoActionPerformed

    private void entregadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entregadoActionPerformed
        //jcambio.setEnabled(true);    // TODO add your handling code he
        try {
            String cant;
            cant = entregado.getText();
            float multnum = 0;
            multnum = Float.parseFloat(cant);
            if (multnum <= 0) {
                JOptionPane.showMessageDialog(null, "TIENE QUE SER UN N° POSITIVO Y UN NUMERO MAYOR A CERO ");
                entregado.requestFocus();
            } else {
                
             //   calcular();
            }
        } catch (Exception e) {
            //    getToolkit().beep();
        }

    }//GEN-LAST:event_entregadoActionPerformed

    private void entregadoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_entregadoKeyPressed
        if (evt.getKeyCode() == 10) { // presiona ENTER
            ////fin verificacion
            float subtotal;
            subtotal = Float.parseFloat(entregado.getText()) - Float.parseFloat(Saldo.getText());
 
            if(subtotal > 0){
                Saldo.setText("0");
                montoCobrar.setText("0");
                cambio.setText(String.valueOf(subtotal));
                cobros.txtcambio122233.setText(String.valueOf(subtotal).replace(".0", ""));
                cobros.txtcambio1.setText(String.valueOf(subtotal).replace(".0", ""));
                cobros.txtpagado.setText(entregado.getText().replace(".0", ""));
                 validadPago();
                
                
            } if(subtotal == 0){
                 Saldo.setText("0");
                 montoCobrar.setText("0");
                 cambio.setText("0");
                cobros.txtcambio122233.setText(String.valueOf(subtotal));
                cobros.txtcambio1.setText(String.valueOf(subtotal));
                cobros.txtpagado.setText(entregado.getText());
                  validadPago();
                
            }
                        // this.grabar.setEnabled(true);
            // grabar.doClick();
        }
    }//GEN-LAST:event_entregadoKeyPressed

    private void cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cambioActionPerformed

    private void montoCobrarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoCobrarKeyPressed

        // TODO add your handling code here:
    }//GEN-LAST:event_montoCobrarKeyPressed

    private void btcobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcobrarActionPerformed
        // TODO add your handling code here:
        calcular();
        dehabilitarBilletes();
        validadPago();

        //grabar();
        //  recorrergrilla();
        //  grabar_ventas();
    }//GEN-LAST:event_btcobrarActionPerformed

    private void B10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B10000ActionPerformed
        // TODO add your handling code here
        actual = Float.parseFloat(this.entregado.getText());
        acumulado = (actual + billete10000);
        this.entregado.setText(String.valueOf(acumulado));
        habilitar_boton();
    }//GEN-LAST:event_B10000ActionPerformed

    private void B20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B20000ActionPerformed
        // TODO add your handling code here:
        actual = Float.parseFloat(this.entregado.getText());
        acumulado = (actual + billete20000);
        this.entregado.setText(String.valueOf(acumulado));
        habilitar_boton();

    }//GEN-LAST:event_B20000ActionPerformed

    private void B50000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B50000ActionPerformed
        // TODO add your handling code here:
        actual = Float.parseFloat(this.entregado.getText());
        acumulado = (actual + billete50000);
        this.entregado.setText(String.valueOf(acumulado));
        habilitar_boton();
    }//GEN-LAST:event_B50000ActionPerformed

    private void B100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B100000ActionPerformed
        // TODO add your handling code here:
        actual = Float.parseFloat(this.entregado.getText());
        acumulado = (actual + billete100000);
        this.entregado.setText(String.valueOf(acumulado));
        habilitar_boton();

    }//GEN-LAST:event_B100000ActionPerformed

    private void montoCobrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoCobrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoCobrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cobrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cobrar().setVisible(true);
            }
        });
    }
    float billete10000 = 10000;
    float billete100000 = 100000;
    float billete20000 = 20000;
    float billete50000 = 50000;
    float actual = 0;
    float acumulado = 0;
    float vuelto = 0;
    float importepagado = 0;
    float saldo = 0;
    float importeCobrar = 0;
    float operacion = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B10000;
    private javax.swing.JButton B100000;
    private javax.swing.JButton B20000;
    private javax.swing.JButton B50000;
    public static javax.swing.JTextField Saldo;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bsalir;
    private javax.swing.JButton btcobrar;
    private javax.swing.JTextField cambio;
    private javax.swing.JTextField entregado;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jcambio;
    private javax.swing.JPanel jentregado;
    private javax.swing.JPanel jmonto;
    public static javax.swing.JTextField montoCobrar;
    // End of variables declaration//GEN-END:variables

    private void habilitar_boton() {
        // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        if (Float.parseFloat(entregado.getText()) >= Float.parseFloat(Saldo.getText())) {
            btcobrar.setEnabled(true);
            btcobrar.requestFocus();

        }
    }

    /*private void tirar_grillas2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }*/
    private void calcular() {
        importepagado = Float.parseFloat(this.entregado.getText());
        saldo = Float.parseFloat(cobrar.Saldo.getText());
        importeCobrar = Float.parseFloat(cobrar.montoCobrar.getText());
        operacion = (importepagado - importeCobrar);

        
        if (operacion > 0) {
            cobros.txtpagado.setText(this.entregado.getText());
            cobrar.Saldo.setText("0");
            cobrar.montoCobrar.setText("0");
            this.entregado.setText("0");
            this.entregado.setEnabled(false);
            this.cambio.setText(String.valueOf(operacion));
            cobros.txtcambio122233.setText(this.cambio.getText().replace(".0", ""));
            cobros.txtcambio1.setText(this.cambio.getText().replace(".0", ""));
            cobros.txtsaldo.setText(cobrar.Saldo.getText().replace(".0", ""));
            
        }  if (operacion < 0) {
            cobrar.Saldo.setText(String.valueOf(operacion * -1));
            cobrar.montoCobrar.setText(String.valueOf(operacion * -1));
            this.cambio.setText("0");
            this.entregado.setText("0");
            entregado.requestFocus();
            this.entregado.setText("0");
            
        }  if (operacion == 0) {
             this.cambio.setText("0");
            this.entregado.setText("0");
            cobrar.montoCobrar.setText("0");
            cobrar.Saldo.setText("0");
            cobros.txtcambio122233.setText(this.cambio.getText().replace(".0", ""));
            cobros.txtcambio1.setText(this.cambio.getText().replace(".0", ""));
            cobros.txtsaldo.setText(cobrar.Saldo.getText().replace(".0", ""));

        }
    }

    private void dehabilitarBilletes() {
        saldo = Integer.parseInt(cobrar.Saldo.getText());
        if (saldo == 0) {
            this.B10000.setEnabled(false);
            this.B20000.setEnabled(false);
            this.B50000.setEnabled(false);
            this.B100000.setEnabled(false);
            dispose();

        }
    }

    private void validadPago() {
        if (Float.parseFloat(Saldo.getText()) < 1) {
            cobros.BGravar1.setEnabled(true);
            dispose();
        }
    }
    
    
}
