/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static formularios.cobros.Total;
import static formularios.menupri.usucodigo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import programas.conexion;
import programas.ver_conex;

/**
 *
 * @author Eduardo Avila
 */
public class compras extends javax.swing.JFrame {

    ver_conex conn = new ver_conex();
    //publicamos el cursor
    javax.swing.table.DefaultTableModel cursor;
    int c;
    int id_detalle;

    /**
     * Creates new form compras
     */
    public compras() {
        initComponents();
        cursor = (javax.swing.table.DefaultTableModel) grilla.getModel();
        des_text();
        txtcodsucursal.setText(acceso.ususucur);
        txtsucurdescri.setText(acceso.sucurdescri);
        txtcodper.setText(acceso.usucod);
        lnombre.setText(acceso.usunom);

        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        fechas.setText(acceso.fechasistema);
        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        this.setLocationRelativeTo(null);
        hab_botones();
        Timer time = new Timer(250, new escucha());
        time.start();
        int c;
        fecha();
    }

    class escucha implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar ahora = Calendar.getInstance();
            int hor = ahora.get(Calendar.HOUR_OF_DAY);
            int min = ahora.get(Calendar.MINUTE);
            int seg = ahora.get(Calendar.SECOND);
            // hora.setText(hor + ":" + min + ":" + seg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lcodigo2 = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        lcodigo3 = new javax.swing.JLabel();
        txtcodsucursal = new javax.swing.JTextField();
        txtsucurdescri = new javax.swing.JTextField();
        txtcodper = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechas = new javax.swing.JTextField();
        txthora = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        bgrabar = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        bborrar = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        Total = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtbarra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcosto = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPrecioVenta = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnroFactura = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo Producto:");

        txtcantidad.setEnabled(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad :");

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lcodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo.setText("Sucursal");

        txtcodigo.setEditable(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        lcodigo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo2.setText("Codigo :");

        lnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lnombre.setText("Nombre");

        lcodigo3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo3.setText("Usuario:");

        txtcodsucursal.setEditable(false);
        txtcodsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodsucursalActionPerformed(evt);
            }
        });
        txtcodsucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyTyped(evt);
            }
        });

        txtsucurdescri.setEditable(false);

        txtcodper.setEditable(false);
        txtcodper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodperActionPerformed(evt);
            }
        });
        txtcodper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodperKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodperKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Fecha :");

        fechas.setEditable(false);
        fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasActionPerformed(evt);
            }
        });
        fechas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechasKeyTyped(evt);
            }
        });

        txthora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txthora.setText("HORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcodigo2)
                .addGap(8, 8, 8)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lcodigo3)
                .addGap(7, 7, 7)
                .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnombre)
                .addGap(18, 18, 18)
                .addComponent(lcodigo)
                .addGap(18, 18, 18)
                .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 219, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcodigo2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lcodigo)
                        .addComponent(lnombre)
                        .addComponent(lcodigo3)
                        .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtdescripcion.setEditable(false);
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        grilla.setBackground(new java.awt.Color(102, 255, 255));
        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Id Producto", "Barra", "Descripcion", "Costo", "Precio Venta", "Cantidad", "Importe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla);
        if (grilla.getColumnModel().getColumnCount() > 0) {
            grilla.getColumnModel().getColumn(0).setResizable(false);
            grilla.getColumnModel().getColumn(0).setPreferredWidth(5);
            grilla.getColumnModel().getColumn(1).setResizable(false);
            grilla.getColumnModel().getColumn(2).setResizable(false);
            grilla.getColumnModel().getColumn(3).setResizable(false);
            grilla.getColumnModel().getColumn(3).setPreferredWidth(100);
            grilla.getColumnModel().getColumn(4).setResizable(false);
            grilla.getColumnModel().getColumn(5).setResizable(false);
            grilla.getColumnModel().getColumn(6).setResizable(false);
            grilla.getColumnModel().getColumn(7).setResizable(false);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_90894.png"))); // NOI18N
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        bcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_icon-icons.com_73703.png"))); // NOI18N
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bgrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });

        bagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bagregar)
                .addGap(18, 18, 18)
                .addComponent(bgrabar)
                .addGap(18, 18, 18)
                .addComponent(bcancelar)
                .addGap(18, 18, 18)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalir)
                    .addComponent(bagregar)
                    .addComponent(bgrabar)
                    .addComponent(bcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bborrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bborrar.setText("Borrar item");
        bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrarActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("TOTAL:");

        Total.setEditable(false);
        Total.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Total.setText("0");
        Total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TotalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(bborrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Total, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Registro de compras");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtbarra.setEnabled(false);
        txtbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarraActionPerformed(evt);
            }
        });
        txtbarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbarraKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Costo:");

        txtcosto.setEnabled(false);
        txtcosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcostoActionPerformed(evt);
            }
        });
        txtcosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcostoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcostoKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Precio Venta:");

        txtPrecioVenta.setEnabled(false);
        txtPrecioVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVentaActionPerformed(evt);
            }
        });
        txtPrecioVenta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioVentaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nro de Factura:");

        txtnroFactura.setEnabled(false);
        txtnroFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnroFacturaActionPerformed(evt);
            }
        });
        txtnroFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnroFacturaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnroFacturaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(410, 410, 410)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(73, 73, 73)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtnroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnroFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecioVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
        limpiargrilla();
        limpiarTextos();
        bgrabar.setEnabled(false);
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        operacion = "agregar";
        gencod();
        mostrar_fecha();
        txtnroFactura.setEnabled(true);
        txtnroFactura.requestFocus();
        bagregar.setEnabled(false);
    }//GEN-LAST:event_bagregarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
   
                tirar_grillas();
                sumarColumna();
                bcancelar.setEnabled(true);
                bgrabar.setEnabled(true);
                txtbarra.requestFocus();
                
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed

        if (evt.getKeyCode() == 10) { // presiona ENTER

            ////fin verificacion
            int subtotal;
            //  subtotal = Integer.parseInt(txtcantidad.getText()) * Integer.parseInt(txtprecio.getText());

            //    total = total + subtotal;
            // txttotal.setText(String.valueOf(total));
            //  Total3.setText(String.valueOf(total));
            //      txtletras.setText(numero.nletra(total));
            /////tira a la grilla
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
        // busca_detalle();
        //   beditar.setEnabled(true);
        bgrabar.setEnabled(false);
        //    buscarcompras();
        //  txttotal.setEnabled(false);
        txtdescripcion.setEnabled(false);
        //  txtmercacod.requestFocus();
        txtcodigo.setEnabled(false);
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodsucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalActionPerformed

    private void txtcodsucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyPressed

    private void txtcodsucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyTyped

    private void txtcodperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperActionPerformed

    private void txtcodperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyPressed

    private void txtcodperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyTyped

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
//        buscar_cod();
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdescripcionKeyTyped

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechasActionPerformed
        // TODO add your handling code here:
        fechas.setEnabled(false);
        bgrabar.setEnabled(true);
        bgrabar.requestFocus();
    }//GEN-LAST:event_fechasActionPerformed

    private void fechasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyTyped

    private void fechasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyPressed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_bsalirActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarraActionPerformed
        // TODO add your handling code here:
        buscarArticulo();

    }//GEN-LAST:event_txtbarraActionPerformed

    private void txtbarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyPressed
        // TODO add your handling code here:
        if (txtbarra.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        {
            JTextField[] tfParam = new JTextField[2];
            tfParam[0] = this.txtbarra;
            VentanaBuscar buscador = new VentanaBuscar("SELECT BARRA, concat(UPPER(descripcion), '  -  ' , precio_venta) AS descripcion\n"
                    + "FROM producto where descripcion like  ", new String[]{"CODIGO PRODUCTO", "NOMBRE PRODUCTO"}, 2, tfParam);
            buscador.setTitle("Buscar PRODUCTOS");
            buscador.setVisible(true);
        }
    }//GEN-LAST:event_txtbarraKeyPressed

    private void txtbarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarraKeyTyped

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        // TODO add your handling code here:
        validarfecha();
        grabar();
        gencodDetalle();
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrarActionPerformed
        // TODO add your handling code here:
        cursor.removeRow(grilla.getSelectedRow());
        sumarColumna();
    }//GEN-LAST:event_bborrarActionPerformed

    private void txtcostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcostoActionPerformed
        // TODO add your handling code here:
        txtPrecioVenta.setEnabled(true);
        txtPrecioVenta.requestFocus();
    }//GEN-LAST:event_txtcostoActionPerformed

    private void txtcostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoKeyPressed

    private void txtcostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcostoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcostoKeyTyped

    private void txtPrecioVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVentaActionPerformed
        // TODO add your handling code here:
        txtcantidad.setEnabled(true);
        txtcantidad.requestFocus();
    }//GEN-LAST:event_txtPrecioVentaActionPerformed

    private void txtPrecioVentaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaKeyPressed

    private void txtPrecioVentaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioVentaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVentaKeyTyped

    private void txtnroFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnroFacturaActionPerformed
        // TODO add your handling code here:
         txtbarra.setEnabled(true);
         txtbarra.requestFocus();
    }//GEN-LAST:event_txtnroFacturaActionPerformed

    private void txtnroFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnroFacturaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroFacturaKeyPressed

    private void txtnroFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnroFacturaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnroFacturaKeyTyped

    private void TotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compras().setVisible(true);
            }
        });
    }
    public String operacion = "";
    public int acu;
    public int aux;
    public int subtotal;
    public int iva = 0;
    public int total = 0, totaliva5, totaliva10, totaliva, ban;
    public String cant, precio;
    public String iva5, iva10, extend, a1, a2, a3, a4, a5;
    public int condicion = 0;
    public String cantidad = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Total;
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bborrar;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fechas;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcodigo2;
    private javax.swing.JLabel lcodigo3;
    private javax.swing.JLabel lnombre;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtPrecioVenta;
    private javax.swing.JTextField txtbarra;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodper;
    private javax.swing.JTextField txtcodsucursal;
    private javax.swing.JTextField txtcosto;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txthora;
    private javax.swing.JTextField txtnroFactura;
    private javax.swing.JTextField txtsucurdescri;
    // End of variables declaration//GEN-END:variables

   

    private void des_text() {
        txtcodigo.setEnabled(false);
        fechas.setEnabled(false);
        txtdescripcion.setEnabled(false);
        fechas.setEnabled(false);
        txtcantidad.setEnabled(false);
        txtbarra.setEnabled(false);
        txtPrecioVenta.setEnabled(false);
        txtnroFactura.setEnabled(false);

    }


    private void des_botones() //metodo para deshabilitar botones
    {
        bagregar.setEnabled(false);
        bgrabar.setEnabled(false);
        bsalir.setEnabled(true);
        bcancelar.setEnabled(true);
    }

    private void hab_botones() // metodo para hab botones
    {
        bagregar.setEnabled(true);
        bgrabar.setEnabled(false);
        bcancelar.setEnabled(false);
        bsalir.setEnabled(true);

    }

    private void mostrar_fecha() {

        try {
            ver_conex c = new ver_conex();
            c.sentencia = c.conexion.createStatement();
            c.resultado = c.sentencia.executeQuery("select date_format(current_date(),'%d/%m/%Y') as fecha");
            while (c.resultado.next()) {
                fechas.setText(c.resultado.getString("fecha"));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void gencod() {
        try {
            //       Main.inicio = "no";
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+ 1 AS xxx FROM cabecera_compras");
            conn.resultado.next();
            this.txtcodigo.setText(conn.resultado.getString("xxx"));
        } catch (SQLException ex) {
            Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            //   } catch (SQLException ex)
            {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void validarfecha() {
        String fecha11 = fechas.getText();

        if (fecha11.equals("")) {
            mensajeValidar(this, "\"FECHA\"");

        }

    }

    private static void mensajeValidar(JFrame x, String campo) {
        JOptionPane.showMessageDialog(x, "El campo " + campo + " no puede estar vacío-cargue y luego guarde! ", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
    }

    private static void mensajeValidarGrilla(JFrame x, String campo) {
        JOptionPane.showMessageDialog(x, "Debe añadir datos en la " + campo + " antes de continuar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }
    public int exenta1 = 0, iva51 = 0, iva101 = 0;
    public int totalexenta = 0,
            totiva = 0,
            Subtotal;



    private void limpiargrilla() {
        for (int i = grilla.getRowCount() - 1; i >= 0; i--) {
            cursor.removeRow(i);
        }
    }

    private void grabar() {
        int res = javax.swing.JOptionPane.showOptionDialog(this,
                "Desea grabar la Factura de Compra?", "Producsys", javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Si", "No"}, "Si");

        if (res == javax.swing.JOptionPane.OK_OPTION) {

            try {

                ver_conex conn = new ver_conex();
                conn.sentencia = conn.conexion.createStatement();
                gencod();  // sirve para que no se dupliquen los codigos y no de error cuando se trabaja en redes
                conn.sentencia.executeUpdate("INSERT INTO cabecera_compras(id,fecha,hora,nro_factura,id_proveedor,total_factura,condicion,usu_cod,suc_cod,estado) "
                        + "values(" + txtcodigo.getText() + ",'" + fechas.getText() + "','" + txthora.getText() + "','" + txtnroFactura.getText() + "'," + 1 + ","
                        + 0 + "," + "'1'" + "," + txtcodper.getText() + "," + txtcodsucursal.getText() + "," + "'1'" + ")");
                gencodDetalle();
                //graba en el detalle
                for (int fila = 0; fila < grilla.getRowCount(); fila++) {
                    gencodDetalle();
                    conn.sentencia.executeUpdate("insert into detalle_compras(id,id_cabecera,item,id_producto,barra_producto,precio,cantidad,total,estado)values(" + id_detalle + "," + txtcodigo.getText() + "," + grilla.getValueAt(fila, 0) + "," + grilla.getValueAt(fila, 1) + "," + grilla.getValueAt(fila, 2) + "," + grilla.getValueAt(fila, 4) + "," + grilla.getValueAt(fila, 6) + "," + grilla.getValueAt(fila, 7) + "," + 1 + ")");
                    conn.sentencia.executeUpdate("update producto set precio_venta = " + grilla.getValueAt(fila, 5) + " where prd_cod = " + grilla.getValueAt(fila, 1));

                }
                JOptionPane.showMessageDialog(null, "La compra fue grabada Satisfactoriamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                limpiargrilla();
                limpiarTextos();

                des_text();
                bgrabar.setEnabled(false);
                bagregar.setEnabled(true);

            } catch (Exception ex) {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Operacion Cancelada", "Atencion", JOptionPane.ERROR_MESSAGE);
        }
    }


    public void buscarArticulo() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT PRD_COD,DESCRIPCION,BARRA, PRECIO_VENTA \n"
                    + "FROM PRODUCTO\n"
                    + "WHERE BARRA = " + this.txtbarra.getText());

            if (conn.resultado.next())//si encontro
            {
                this.txtbarra.setText(conn.resultado.getString("BARRA"));
                this.txtID.setText(conn.resultado.getString("PRD_COD"));
                this.txtPrecioVenta.setText(conn.resultado.getString("PRECIO_VENTA"));
                this.txtdescripcion.setText(conn.resultado.getString("DESCRIPCION"));
                txtcosto.setEnabled(true);
                txtcosto.requestFocus();

                //   this.txtdepdescri.setText(conn.resultado.getString("depo_desc"));
            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "El codigo ingresado aun no esta Registrado");
                txtbarra.requestFocus();

            }

        } catch (SQLException exceptionSql) {
            //   JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void tirar_grillas() {
        try {
            do {
                c++;
                DefaultTableModel dt;
                dt = (DefaultTableModel) grilla.getModel();
                
                float valorCantidad = 0;
                float valorPrecio = 0;
                
                valorPrecio = Float.valueOf(txtcosto.getText());
                valorCantidad = Float.valueOf(txtcantidad.getText());
                
                String campos[] = new String[]{String.valueOf(c), txtID.getText(), txtbarra.getText(), 
                    txtdescripcion.getText(), txtcosto.getText(), txtPrecioVenta.getText(), txtcantidad.getText() ,
                String.valueOf( Math.round(valorPrecio * valorCantidad ) )
                };
                dt.addRow(campos);
            } while (conn.resultado.next());
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        txtcantidad.setEnabled(false);

        txtcantidad.setText("");
        txtPrecioVenta.setText("");
        txtdescripcion.setText("");
        txtID.setText("");
        txtbarra.setText("");
        txtcosto.setText("");
    }

    private void fecha() {
        try {
            ver_conex conn = new ver_conex();//instanciamos current_date()  (curdate())
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select date_format(current_date(),'%Y/%m/%d') as fecha");
            conn.resultado.next();
            fechas.setText(conn.resultado.getString("fecha"));
            Hora1();

        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
            // System.exit(0);
        }
    }//fin generar

    private void Hora1() {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select curtime() as hora");
            conn.resultado.next();
            txthora.setText(conn.resultado.getString("hora"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private void gencodDetalle() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+1 AS newcod ,CURDATE() AS fecha FROM detalle_compras");
            conn.resultado.next();
            id_detalle = Integer.parseInt(conn.resultado.getString("newcod"));
        } //fin generar
        catch (SQLException ex) {
            //   Logger.getLogger(facturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void sumarColumna() {
        int fila;
        int total = 0;

        for (int i = 0; i < grilla.getRowCount(); i++) {
            fila = Integer.parseInt(grilla.getValueAt(i, 7).toString());
            total += fila;
             Total.setText(String.valueOf(total));

        }

    }

    private void salir() {
        int respuesta = JOptionPane.showConfirmDialog(this, "DESEA SALIR", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();

        }

    }

    private void limpiarTextos() {

        txtbarra.setText("");
        txtID.setText("");
        txtdescripcion.setText("");
        txtcosto.setText("");
        txtcantidad.setText("");
        txtPrecioVenta.setText("");
        txtnroFactura.setText("");
    }
}
