/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import static formularios.cobros.Total;
import static formularios.menupri.usucodigo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import programas.conexion;
import programas.ver_conex;

/**
 *
 * @author hp
 */
public class compras extends javax.swing.JFrame {

    ver_conex conn = new ver_conex();
    //publicamos el cursor
    javax.swing.table.DefaultTableModel cursor;
    int c;
    int id_detalle;

    /**
     * Creates new form compras
     */
    public compras() {
        initComponents();
        cursor = (javax.swing.table.DefaultTableModel) grilla.getModel();
        des_text();
//      lfecha.setText(acceso.fechasistema);
//        fecha.setText(acceso.fechasistema);
        txtcodsucursal.setText(acceso.ususucur);
        txtsucurdescri.setText(acceso.sucurdescri);
        txtcodper.setText(acceso.usucod);
        lnombre.setText(acceso.usunom);

        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        //  lfecha.setText(acceso.fechasistema);
        fechas.setText(acceso.fechasistema);
        // txtcodsucursal.setText(acceso.ususucur);
        // txtsucurdescri.setText(acceso.sucurdescri);
        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        this.setLocationRelativeTo(null);
        hab_botones();
        Timer time = new Timer(250, new escucha());
        time.start();
        int c;
        fecha();
    }

    class escucha implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar ahora = Calendar.getInstance();
            int hor = ahora.get(Calendar.HOUR_OF_DAY);
            int min = ahora.get(Calendar.MINUTE);
            int seg = ahora.get(Calendar.SECOND);
            // hora.setText(hor + ":" + min + ":" + seg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lcodigo2 = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        lcodigo3 = new javax.swing.JLabel();
        txtcodsucursal = new javax.swing.JTextField();
        txtsucurdescri = new javax.swing.JTextField();
        txtcodper = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechas = new javax.swing.JTextField();
        txthora = new javax.swing.JLabel();
        txtdescripcion = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        bsalir = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        bgrabar = new javax.swing.JButton();
        bagregar = new javax.swing.JButton();
        bborrar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        txtbarra = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtCosto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo Producto:");

        txtcantidad.setEnabled(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad :");

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lcodigo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lcodigo.setText("Sucursal");

        txtcodigo.setEditable(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        lcodigo2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lcodigo2.setText("Codigo :");

        lnombre.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lnombre.setText("Nombre");

        lcodigo3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lcodigo3.setText("Usuario:");

        txtcodsucursal.setEditable(false);
        txtcodsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodsucursalActionPerformed(evt);
            }
        });
        txtcodsucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyTyped(evt);
            }
        });

        txtsucurdescri.setEditable(false);

        txtcodper.setEditable(false);
        txtcodper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodperActionPerformed(evt);
            }
        });
        txtcodper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodperKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodperKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setText("Fecha :");

        fechas.setEditable(false);
        fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasActionPerformed(evt);
            }
        });
        fechas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechasKeyTyped(evt);
            }
        });

        txthora.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txthora.setText("HORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcodigo2)
                .addGap(8, 8, 8)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lcodigo3)
                .addGap(7, 7, 7)
                .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnombre)
                .addGap(18, 18, 18)
                .addComponent(lcodigo)
                .addGap(18, 18, 18)
                .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcodigo2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lcodigo)
                        .addComponent(lnombre)
                        .addComponent(lcodigo3)
                        .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtdescripcion.setEditable(false);
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        grilla.setBackground(new java.awt.Color(102, 255, 255));
        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Id Producto", "Barra", "Descripcion", "Costo", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla);
        if (grilla.getColumnModel().getColumnCount() > 0) {
            grilla.getColumnModel().getColumn(0).setResizable(false);
            grilla.getColumnModel().getColumn(0).setPreferredWidth(5);
            grilla.getColumnModel().getColumn(1).setResizable(false);
            grilla.getColumnModel().getColumn(2).setResizable(false);
            grilla.getColumnModel().getColumn(3).setResizable(false);
            grilla.getColumnModel().getColumn(3).setPreferredWidth(100);
            grilla.getColumnModel().getColumn(4).setResizable(false);
            grilla.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        bsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_90894.png"))); // NOI18N
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        bcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_icon-icons.com_73703.png"))); // NOI18N
        bcancelar.setEnabled(false);
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bgrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        bgrabar.setEnabled(false);
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });

        bagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(569, Short.MAX_VALUE)
                .addComponent(bagregar)
                .addGap(18, 18, 18)
                .addComponent(bgrabar)
                .addGap(18, 18, 18)
                .addComponent(bcancelar)
                .addGap(18, 18, 18)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalir)
                    .addComponent(bagregar)
                    .addComponent(bgrabar)
                    .addComponent(bcancelar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bborrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bborrar.setText("Borrar item");
        bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(bborrar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Registro de compras");

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtbarra.setEnabled(false);
        txtbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarraActionPerformed(evt);
            }
        });
        txtbarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbarraKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Costo:");

        txtCosto.setEnabled(false);
        txtCosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostoActionPerformed(evt);
            }
        });
        txtCosto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCostoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCostoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtdescripcion)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCosto, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(410, 410, 410)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtcantidad, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCosto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
                limpiargrilla();
                limpiarTextos();
                
                bgrabar.setEnabled(false);
                bagregar.setEnabled(true);
               bcancelar.setEnabled(false);
               
               txtbarra.setEnabled(false);
               txtCosto.setEnabled(false);
               txtcantidad.setEnabled(false);
                              
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        operacion = "agregar";
        gencod();
        mostrar_fecha();
        txtbarra.setEnabled(true);
        txtbarra.requestFocus();
        bagregar.setEnabled(false);
    }//GEN-LAST:event_bagregarActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    
               tirar_grillas();
               bcancelar.setEnabled(true);
               bgrabar.setEnabled(true);
               txtbarra.requestFocus();

    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed

        if (evt.getKeyCode() == 10) { // presiona ENTER
          
            ////fin verificacion
            int subtotal;
          //  subtotal = Integer.parseInt(txtcantidad.getText()) * Integer.parseInt(txtprecio.getText());

        //    total = total + subtotal;

           // txttotal.setText(String.valueOf(total));
            //  Total3.setText(String.valueOf(total));

      //      txtletras.setText(numero.nletra(total));

            /////tira a la grilla
          
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
        // busca_detalle();
        //   beditar.setEnabled(true);
        bgrabar.setEnabled(false);
        //    buscarcompras();
      //  txttotal.setEnabled(false);
        txtdescripcion.setEnabled(false);
        //  txtmercacod.requestFocus();
        txtcodigo.setEnabled(false);
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodsucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalActionPerformed

    private void txtcodsucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyPressed

    private void txtcodsucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyTyped

    private void txtcodperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperActionPerformed

    private void txtcodperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyPressed

    private void txtcodperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyTyped

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
//        buscar_cod();
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdescripcionKeyTyped

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        // TODO add your handling code here:
////        if (txtmercacod.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER) {// presiona F12
////            new bus_art(null,true).setVisible(true);// llama al buscador
////
////            if (bus_art.vdes.isEmpty())//no trae nada
////            {
////                return;
////            }else // trae datos
////            {
////                txtmercacod.setText(bus_art.vcod);
////                txtdescri.setText((bus_art.vdes));
////                //  txtprecio.setText(bus_art.vprecio);
////                // txttotal.requestFocus();
////
////            }
////        }//fin F12
////
////        if(evt.getKeyCode()==35) { // presiona TECLA FIN
////            bgrabar.setEnabled(true);
////            //  bgrabar.requestFocus();
////            txtcantidad.setEnabled(true);
////            txtcantidad.requestFocus();
////        }
////        //          if (txtmerca.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
////        //        {
////            //            JTextField[] tfParam = new JTextField[2];
////            //            tfParam[0] = this.txtmerca;
////            //            tfParam[1] = this.txtdescri;
////            //            VentanaBuscar buscador = new VentanaBuscar("select mer_cod,mer_nom from mercaderia where mer_nom like  ", new String[]{"CODIGO marca", "NOMBRE marca ACTIVO"}, 2, tfParam);
////            //            buscador.setTitle("Buscar Merca");
////            //            buscador.setVisible(true);
////            //    }
    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechasActionPerformed
        // TODO add your handling code here:
        //  txtmercacod.requestFocus();
        fechas.setEnabled(false);
        bgrabar.setEnabled(true);
        bgrabar.requestFocus();
    }//GEN-LAST:event_fechasActionPerformed

    private void fechasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyTyped

    private void fechasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyPressed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
       salir();
    }//GEN-LAST:event_bsalirActionPerformed

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:

       
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarraActionPerformed
        // TODO add your handling code here:
        buscarArticulo();
       
    }//GEN-LAST:event_txtbarraActionPerformed

    private void txtbarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyPressed
        // TODO add your handling code here:
            if (txtbarra.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        {
            JTextField[] tfParam = new JTextField[2];
            tfParam[0] = this.txtbarra;
 VentanaBuscar buscador = new VentanaBuscar("SELECT BARRA,UPPER(descripcion)AS descripcion\n"
                    + "FROM producto where descripcion like  ", new String[]{"CODIGO PRODUCTO", "NOMBRE PRODUCTO"}, 2, tfParam);
            buscador.setTitle("Buscar PRODUCTOS");
            buscador.setVisible(true);
            buscador.setVisible(true);
        }
    }//GEN-LAST:event_txtbarraKeyPressed

    private void txtbarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarraKeyTyped

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        // TODO add your handling code here:
        validarfecha();
        //grabar();
        grabar();
        gencodDetalle();
        //suma_stock();
        // borrar_text();
        //        limpiartextgrilla();
        //limpiargrilla();
        //bcancelar.doClick();
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrarActionPerformed
        // TODO add your handling code here:
         cursor.removeRow(grilla.getSelectedRow());
    sumarColumna();
    }//GEN-LAST:event_bborrarActionPerformed

    private void txtCostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostoActionPerformed
        // TODO add your handling code here:
        txtcantidad.setEnabled(true);
        txtcantidad.requestFocus();
    }//GEN-LAST:event_txtCostoActionPerformed

    private void txtCostoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoKeyPressed

    private void txtCostoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCostoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(compras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new compras().setVisible(true);
            }
        });
    }
    public String operacion = "";
    public int acu;
    public int aux;
    public int subtotal;
    public int iva = 0;
    public int total = 0, totaliva5, totaliva10, totaliva, ban;
    // public String iva = "";
    //public int total, totaliva5, totaliva10, totaliva, ban;
    public String cant, precio;
    public String iva5, iva10, extend, a1, a2, a3, a4, a5;
    public int condicion = 0;
    public String cantidad = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bborrar;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bsalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField fechas;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcodigo2;
    private javax.swing.JLabel lcodigo3;
    private javax.swing.JLabel lnombre;
    private javax.swing.JTextField txtCosto;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtbarra;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodper;
    private javax.swing.JTextField txtcodsucursal;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JLabel txthora;
    private javax.swing.JTextField txtsucurdescri;
    // End of variables declaration//GEN-END:variables

    private void hab_text() {
//        txtcodigo.setEnabled(true);
//        txtprocod.setEnabled(false);
//        //combodeposito.setEnabled(true);
//        fecha.setEnabled(true);
//        txtmercacod.setEnabled(false);
    }

    private void des_text() {
        txtcodigo.setEnabled(false);
       
        fechas.setEnabled(false);
        txtdescripcion.setEnabled(false);
       
        fechas.setEnabled(false);

        txtcantidad.setEnabled(false);
     
         txtbarra.setEnabled(false);

    }

    
    
    private void borrar_text() {
        // txtimbrado.setText("");
        txtcantidad.setText("");
        txtcodigo.setText("");
     
        fechas.setText("");
        txtdescripcion.setText("");

   //     txttotal.setText("");
        fechas.setText("");
      
        txtdescripcion.setText("");
    //    txttotal.setText("");
    //    txtletras.setText("");

        //txtsucurdescri.setText("");
    }

    private void des_botones() //metodo para deshabilitar botones
    {
        bagregar.setEnabled(false);
        // bmercaderia.setEnabled(false);
        // bproveedor.setEnabled(false);
        bgrabar.setEnabled(false);
        bsalir.setEnabled(true);
        bcancelar.setEnabled(true);
    }

    private void hab_botones() // metodo para hab botones
    {
        bagregar.setEnabled(true);
        bgrabar.setEnabled(false);
        bcancelar.setEnabled(false);
        bsalir.setEnabled(true);

    }

    private void mostrar_fecha() {

        try {
            ver_conex c = new ver_conex();
            c.sentencia = c.conexion.createStatement();
            c.resultado = c.sentencia.executeQuery("select date_format(current_date(),'%d/%m/%Y') as fecha");
            while (c.resultado.next()) {
                fechas.setText(c.resultado.getString("fecha"));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void gencod() {
        try {
            //       Main.inicio = "no";
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+ 1 AS xxx FROM cabecera_compras");
            conn.resultado.next();
            this.txtcodigo.setText(conn.resultado.getString("xxx"));
        } catch (SQLException ex) {
            Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            //   } catch (SQLException ex)
            {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }

    private void validarfecha() {
        String fecha11 = fechas.getText();

        if (fecha11.equals("")) {
            mensajeValidar(this, "\"FECHA\"");

        }

    }

    private static void mensajeValidar(JFrame x, String campo) {
        JOptionPane.showMessageDialog(x, "El campo " + campo + " no puede estar vacío-cargue y luego guarde! ", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
    }

  

    private static void mensajeValidarGrilla(JFrame x, String campo) {
        JOptionPane.showMessageDialog(x, "Debe añadir datos en la " + campo + " antes de continuar", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }
    public int exenta1 = 0, iva51 = 0, iva101 = 0;
    public int totalexenta = 0,
            //  totaliva5 = 0,
            // totaliva10 = 0,
            //total=0,
            totiva = 0,
            Subtotal;

    private void calcular_total() {

        for (int a = 0; a < grilla.getRowCount(); a++) {

            String exenta, iva5, iva10, can1, pre1;

//        int re ;
            int can, pre;
//        re=t.getSelectedRow();
            exenta = (String.valueOf(this.grilla.getValueAt(a, 4)));
            iva5 = (String.valueOf(this.grilla.getValueAt(a, 5)));
            iva10 = (String.valueOf(this.grilla.getValueAt(a, 6)));

            can1 = (String.valueOf(this.grilla.getValueAt(a, 3)));
            pre1 = (String.valueOf(this.grilla.getValueAt(a, 2)));

            exenta1 = Integer.parseInt(exenta);
            iva51 = Integer.parseInt(iva5);
            iva101 = Integer.parseInt(iva10);

            can = Integer.parseInt(can1);
            pre = Integer.parseInt(pre1);
            subtotal = (can * pre);
            total = total + subtotal;

            totalexenta = totalexenta + exenta1;
            // txtexenta.setText(String.valueOf(totalexenta));

            totaliva5 = totaliva5 + (iva51 / 21);
            // txtiva5.setText(String.valueOf(totaliva5));

            totaliva10 = totaliva10 + (iva101 / 11);
            // txtiva10.setText(String.valueOf(totaliva10));

            totiva = totaliva5 + totaliva10;
            //    this.txttotaliva.setText(String.valueOf(totiva));

      //      txttotal.setText(String.valueOf(total));
      //      txtletras.setText(numero.nletra(total));

        }

    }

    private void buscar_deposito() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT d.depo_cod, d.depo_desc FROM deposito d, cabecera_oc o WHERE  d.depo_cod=o.depo_cod AND o.oc_cod= 0");

            if (conn.resultado.next())//si encontro
            {

            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "No hay pedido para este deposito", "MENSAJE",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
         //   System.exit(0);
        }
    }
//       private buscarorden()
//    {
//        try {
//            conn.sentencia = conn.conexion.createStatement();
//            conn.resultado = conn.sentencia.executeQuery("select * from orden_com inner join det_orcom on orden_com.or_cod=det_orcom.or_cod inner join mercaderia  on mercaderia.mer_cod=det_orcom.mer_cod inner join proveedor on proveedor.pro_cod=orden_com.pro_cod where  orden_com.or_cod =" + txtcodigo.getText());
//            boolean encontro = conn.resultado.next();
//
//            if (encontro==true)//encontro
//            {
//
//                ver_conex conn4 = new ver_conex();
//                conn4.sentencia = conn4.conexion.createStatement();
//               conn4.resultado = conn4.sentencia.executeQuery  ("SELECT proveedor.pro_cod,proveedor.pro_nom FROM proveedor INNER JOIN orden_com ON proveedor.pro_cod=orden_com.pro_cod WHERE or_cod = "+txtcodigo.getText());
//               boolean encontr = conn4.resultado.next();
//               if(encontr==true){
//                buscar_deposito();
//                 txtprocod.setText(conn4.resultado.getString("pro_cod"));
//                  txtprodescri.setText(conn4.resultado.getString("pro_nom"));
//        //  tirar_grilla();
//                ///mostrar datos del detalle
//            //  ver_conex conn2 = new ver_conex();
//               }
//               ver_conex conn2 =new ver_conex();//instanciamos
//                 conn2.sentencia = conn2.conexion.createStatement();
//                 conn2.resultado = conn2.sentencia.executeQuery("select * from det_orcom  where or_cod =" + txtcodigo.getText());
//
//                 while(conn2.resultado.next())
//                 {
//                    ////para la descricion
//                    ver_conex conn3 =new ver_conex();//instanciamos
//                    conn3.sentencia = conn3.conexion.createStatement();
//                    conn3.resultado = conn3.sentencia.executeQuery("select * from mercaderia  where mer_cod =" + conn2.resultado.getString("mer_cod"));
//                    conn3.resultado.next();//ubica en el primer registro
//                    int aux = 0;
//                    int cant;
//       int acu = 0;
//       int precio;
//
//// cant= conn2.resultado.getInt("det_orcant");
//// precio=conn2.resultado.getInt("det_orprecio");
//////                    for(int a=0;a<grilla.getRowCount();a++)
//////        {
////           aux = cant * precio;
//////            acu = acu + aux;
////
////        }
//
//
//                    iva=(conn3.resultado.getString("mer_iva"));
//                    if(iva.equals("0")) // exenta
//            {
//                           for(int a=0;a<grilla.getRowCount();a++)
//        {
//           aux = Integer.parseInt(grilla.getValueAt(a,2).toString()) * Integer.parseInt(grilla.getValueAt(a,3).toString());
//            acu = acu + aux;
//
//        }
//                String registro[] = new String[] {conn2.resultado.getString("mer_cod"),conn3.resultado.getString("mer_nom"),conn2.resultado.getString("det_orcant"),conn2.resultado.getString("det_orprecio"),String.valueOf(acu),"0","0"};
//                cursor.addRow(registro);
//            }
//
//            if(iva.equals("5"))//gravada 5%
//            {
//                   for(int a=0;a<grilla.getRowCount();a++)
//        {
//           aux = Integer.parseInt(grilla.getValueAt(a,2).toString()) * Integer.parseInt(grilla.getValueAt(a,3).toString());
//            acu = acu + aux;
//
//        }
//                String registro[] = new String[] {conn2.resultado.getString("mer_cod"),conn3.resultado.getString("mer_nom"),conn2.resultado.getString("det_orcant"),conn2.resultado.getString("det_orprecio"),"0",String.valueOf(acu),"0"};
//                cursor.addRow(registro);
//                totaliva5 = totaliva5 + (acu/21);
//                this.txtiva5.setText(String.valueOf(totaliva5));
//
//            }
//
//            if(iva.equals("10")) // gravada 10 %
//            {
//                  for(int a=0;a<grilla.getRowCount();a++) {
//                    aux = Integer.parseInt(grilla.getValueAt(a,2).toString()) * Integer.parseInt(grilla.getValueAt(a,3).toString());
//
//                  }
//
//            acu = acu + aux;
//
//
//                String registro[] = new String[] {conn2.resultado.getString("mer_cod"),conn3.resultado.getString("mer_nom"),conn2.resultado.getString("det_orcant"),conn2.resultado.getString("det_orprecio"),"0","0",String.valueOf(acu)};
//                cursor.addRow(registro);
//                totaliva10 = totaliva10 + (acu /11);
//                this.txtiva10.setText(String.valueOf(totaliva10));
//              //  return grilla.getRowCount(registro);
//               // return
//            }
//
//            totaliva = totaliva5 + totaliva10;
//            this.txttotaliva.setText(String.valueOf(totaliva));
//
//
//                  //  String registro[] = new String[] {conn2.resultado.getString("mer_cod"),conn3.resultado.getString("mer_nom"),conn2.resultado.getString("det_orcant"),conn2.resultado.getString("det_orprecio"),conn3.resultado.getString("mer_iva")};
//                    ////
//                   // cursor.addRow(registro);
//                    txtcantidad.setEnabled(false);
//                    txtmercacod.setEnabled(true);
//                    txtmercacod.requestFocus();
//                     banular.setEnabled(true);
//                }
//
//
//
//
//                ///mostrar datos del detalle
//
//                   } else{
//              JOptionPane.showMessageDialog(null, " No existe orden con este numero", "Atencion", JOptionPane.ERROR_MESSAGE);
//
//           this.txtcodigo.setEnabled(true);
//          this.txtcodigo.requestFocus();
//        //  banular.setEnabled(true);
//     }
// //   }
//    } catch(SQLException e){
//        JOptionPane.showMessageDialog(null,e.getMessage(), "error de conexion", JOptionPane.ERROR_MESSAGE);
//    }
//    // this.beditar.setEnabled(true);
//    // this.beditar.requestFocus();
////fin de recorrido
////        return buscarorden();
//    }
//

    private void limpiargrilla() {
        for (int i = grilla.getRowCount() - 1; i >= 0; i--) {
            cursor.removeRow(i);
        }
    }

    private void grabar() {
        int res = javax.swing.JOptionPane.showOptionDialog(this,
                "Desea grabar la Factura de Compra?", "Producsys", javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Si", "No"}, "Si");

        if (res == javax.swing.JOptionPane.OK_OPTION) {

            try {
               
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            gencod();  // sirve para que no se dupliquen los codigos y no de error cuando se trabaja en redes
            conn.sentencia.executeUpdate("INSERT INTO cabecera_compras(id,fecha,hora,nro_factura,id_proveedor,total_factura,condicion,usu_cod,suc_cod,estado) "
             + "values(" + txtcodigo.getText() + ",'" + fechas.getText() + "','" + txthora.getText() + "'," +123+ "," +1+ ","
             + 0+ ","+"'1'" +"," + txtcodper.getText() + "," + txtcodsucursal.getText() + "," + "'1'" +")");
            gencodDetalle();
            //graba en el detalle
            for (int fila = 0; fila < grilla.getRowCount(); fila++) {
              gencodDetalle();
              String cantidad = "";
              
              cantidad = grilla.getValueAt(fila, 5).toString().replace(".0", "");
    
                conn.sentencia.executeUpdate("insert into detalle_compras(id,id_cabecera,item,id_producto,barra_producto,precio,cantidad,total,estado)values(" + id_detalle + "," + txtcodigo.getText() + "," + grilla.getValueAt(fila, 0) + "," + grilla.getValueAt(fila, 1) + "," + grilla.getValueAt(fila, 2) + "," +grilla.getValueAt(fila, 4)+ "," + cantidad + "," +0+ "," +1+ ")");

            }
                JOptionPane.showMessageDialog(null, "La compra fue grabada Satisfactoriamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);

                limpiargrilla();
                limpiarTextos();

                des_text();
                bgrabar.setEnabled(false);
                bagregar.setEnabled(true);
                bcancelar.setEnabled(false);

            } catch (Exception ex) {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Operacion Cancelada", "Atencion", JOptionPane.ERROR_MESSAGE);
//}
//if(cbo_condicion.getSelectedItem().equals("CONDICION")) {
//cbo_condicion.setEnabled(false);
//cbo_condicion.requestFocus();
        }

//clear_text();
    }

//               ver_conex conn2 =new ver_conex();//instanciamos
//                 conn2.sentencia = conn2.conexion.createStatement();
//                 conn2.resultado = conn2.sentencia.executeQuery("select * from det_compra  where com_cod =" + txtcodigo.getText());
//
//                 while(conn2.resultado.next())
//                 {
//                    ////para la descricion
//                    ver_conex conn3 =new ver_conex();//instanciamos
//                    conn3.sentencia = conn3.conexion.createStatement();
//                    conn3.resultado = conn3.sentencia.executeQuery("select * from mercaderia  where mer_cod =" + conn2.resultado.getString("mer_cod"));
//                    conn3.resultado.next();//ubica en el primer registro
//                    String registro[] = new String[] {conn2.resultado.getString("mer_cod"),conn3.resultado.getString("mer_nom"),conn2.resultado.getString("det_precio"),conn2.resultado.getString("det_cant"),conn2.resultado.getString("det_graex"),conn2.resultado.getString("det_gra5"),conn2.resultado.getString("det_gra10")};
//                    ////
//                    cursor.addRow(registro);
//                    txtcantidad.setEnabled(false);
//                    txtmercacod.setEnabled(true);
//                    txtmercacod.requestFocus();
//                     banular.setEnabled(true);
//                }
//
//                ///mostrar datos del detalle
//
//                   } else{
//              JOptionPane.showMessageDialog(null, " No existe pedido con este numero", "Atencion", JOptionPane.ERROR_MESSAGE);
//
//           this.txtcodigo.setEnabled(true);
//          this.txtcodigo.requestFocus();
//        //  banular.setEnabled(true);
//     }
// //    }
//    } catch(SQLException e){
//        JOptionPane.showMessageDialog(null,e.getMessage(), "error de conexion", JOptionPane.ERROR_MESSAGE);
//    }
//    // this.beditar.setEnabled(true);
//    // this.beditar.requestFocus();
//}//fin de recorrido
    private void buscar_depositocompra() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT d.depo_cod, d.depo_desc FROM deposito d, cabecera_reg_fact o WHERE  d.depo_cod=o.depo_cod and o.rg_fac_cod=" + this.txtcodigo.getText());

            if (conn.resultado.next())//si encontro
            {
                //   this.txtdepcod.setText(conn.resultado.getString("depo_cod"));
                //   this.txtdepdescri.setText(conn.resultado.getString("depo_desc"));

            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "No hay pedido para este deposito", "MENSAJE",
                        JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
            // System.exit(0);
        }
    }

    private void anularcompras() {

        int res = javax.swing.JOptionPane.showOptionDialog(this,
                "Desea Anular LA COMPRA?", "REGISTRO PEDIDO", javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Si", "No"}, "Si");

        if (res == javax.swing.JOptionPane.OK_OPTION) {

            try {
                //  validarCampos3();

                ver_conex c = new ver_conex();
                c.sentencia = c.conexion.createStatement();
                c.sentencia.executeUpdate("update cabecera_reg_fact set estado='ANULADO' where rg_fac_cod = " + txtcodigo.getText());
                c.sentencia.executeUpdate("update cuentas_a_pagar set estado='ANULADO' where rg_fac_cod = " + txtcodigo.getText());
                //c.sentencia.executeUpdate("UPDATE stock SET stock_cant=stock_cant -" + grilla.getValueAt(fila, 3) + " WHERE prd_cod=" + grilla.getValueAt(fila, 0) + " and suc_cod=" + txtcodsucursal.getText() + " and depo_cod=" + txtdepcod.getText());
                for (int fila = 0; fila < grilla.getRowCount(); fila++) {

                    conn.sentencia.executeUpdate("UPDATE stock SET stock_cant=stock_cant - " + grilla.getValueAt(fila, 3) + " WHERE prd_cod=" + grilla.getValueAt(fila, 0) + " AND depo_cod= 0 ");
                }//
                JOptionPane.showMessageDialog(null, "La compras se ha Anulado satisfactoriamente.", "Confirmacion", JOptionPane.INFORMATION_MESSAGE);

            } catch (SQLException ex) {
                Logger.getLogger(compras.class
                        .getName()).log(Level.SEVERE, null, ex);
            }
        } else {

            JOptionPane.showMessageDialog(null, "Operacion Cancelada", "Atencion", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void actualizar_stock() {
        int cantida = 0;
        try {
            for (int fila = 0; fila < grilla.getRowCount(); fila++) {

                ver_conex c = new ver_conex();
                c.sentencia = c.conexion.createStatement();
                c.resultado = c.sentencia.executeQuery("SELECT * FROM stock WHERE prd_cod=" + grilla.getValueAt(fila, 0) + " and suc_cod=" + txtcodsucursal.getText() + " and depo_cod= 0 ");

                if (c.resultado.next()) {
                    cantida = c.resultado.getInt("stock_cant");

                    c.sentencia.executeUpdate("UPDATE stock SET stock_cant=" + cantida + "-" + grilla.getValueAt(fila, 3) + " WHERE prd_cod=" + grilla.getValueAt(fila, 0) + "");
                } else {
                    //  c.sentencia = c.conexion.createStatement();
                    //c.sentencia.executeUpdate("INSERT INTO stock(mer_cod,suc_cod,dep_cod,cantidad) VALUES("+grilla.getValueAt(fila,0)+","+ txtcodsucursal.getText()+","+ txtdepcod.getText()+","+grilla.getValueAt(fila,3)+")");
                    // insertar_stock();
                }
            }
        } catch (SQLException ex) {
            // Logger.getLogger(FrmCompra.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

   

    public void buscarArticulo() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT PRD_COD,DESCRIPCION,BARRA\n"
                    + "FROM PRODUCTO\n"
                    + "WHERE BARRA = " + this.txtbarra.getText());

            if (conn.resultado.next())//si encontro
            {
                this.txtbarra.setText(conn.resultado.getString("BARRA"));
                this.txtID.setText(conn.resultado.getString("PRD_COD"));
                this.txtdescripcion.setText(conn.resultado.getString("DESCRIPCION"));
                 txtCosto.setEnabled(true);
                  txtCosto.requestFocus();
                
                //   this.txtdepdescri.setText(conn.resultado.getString("depo_desc"));

            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "El codigo ingresado aun no esta Registrado");
                txtbarra.requestFocus();
               
            }

        } catch (SQLException exceptionSql) {
         //   JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
        }

    }
    
     private void tirar_grillas() {
        try {
            do {
                c++;
                  ver_conex conn = new ver_conex();//instanciamos current_date()  (curdate())
                  conn.sentencia = conn.conexion.createStatement();
                DefaultTableModel dt;
                dt = (DefaultTableModel) grilla.getModel();
                String campos[] = new String[]{String.valueOf(c), txtID.getText(), txtbarra.getText(), txtdescripcion.getText(),txtCosto.getText(),txtcantidad.getText()};//cantid
                dt.addRow(campos);
            } while (conn.resultado.next());
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        txtcantidad.setEnabled(false);
        txtCosto.setEnabled(false);
        
        txtcantidad.setText("");
        txtdescripcion.setText("");
        txtID.setText("");
        txtCosto.setText("");
        txtbarra.setText("");
        txtbarra.setText("");
        txtbarra.requestFocus();
        
        
        
    }
          private void fecha() {
        try {
            ver_conex conn = new ver_conex();//instanciamos current_date()  (curdate())
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select date_format(current_date(),'%Y/%m/%d') as fecha");
            conn.resultado.next();
            fechas.setText(conn.resultado.getString("fecha"));
            Hora1();

        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
           // System.exit(0);
        }
    }//fin generar
 private void Hora1() {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select curtime() as hora");
            conn.resultado.next();
            txthora.setText(conn.resultado.getString("hora"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }
     private void gencodDetalle() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+1 AS newcod ,CURDATE() AS fecha FROM detalle_compras");
            conn.resultado.next();
            //this.jTextcod
            //fecha.setText(conn.resultado.getString("fecha"));
            id_detalle = Integer.parseInt(conn.resultado.getString("newcod"));
        } //fin generar
        catch (SQLException ex) {
            //   Logger.getLogger(facturacion.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
       public void sumarColumna(){
        int fila;
        int total = 0;
           
     for (int i = 0; i < grilla.getRowCount(); i++) {
         fila = Integer.parseInt(grilla.getValueAt(i, 6).toString());
          total += fila;
          // txttotal.setText(String.valueOf(total));
    
            }
    
    }
          private void salir (){
     int respuesta = JOptionPane.showConfirmDialog
         (this,"DESEA SALIR","CONFIRMAR",JOptionPane.YES_NO_OPTION);
       if(respuesta == JOptionPane.YES_OPTION)
       {
	   dispose();

       }

}
          
           private void limpiarTextos() {
   
       
        txtbarra.setText("");
        txtID.setText("");
        txtdescripcion.setText("");
        txtCosto.setText("");
        txtcantidad.setText("");
       //txttotal.setText("");
       //txtletras.setText("");
    }
}
