/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import programas.ver_conex;

/**
 *
 * @author
 */
public class Conversiones extends javax.swing.JFrame {

    ver_conex conn = new ver_conex();
    //publicamos el cursor
    javax.swing.table.DefaultTableModel cursor;
    javax.swing.table.DefaultTableModel cursor2;
    int c;
    int c1;
    int id_detalle;

    /**
     * Creates new form Conversiones
     */
    public Conversiones() {
        initComponents();
        cursor = (javax.swing.table.DefaultTableModel) grilla.getModel();
        cursor2 = (javax.swing.table.DefaultTableModel) grilla1.getModel();
        //  des_text();
//      lfecha.setText(acceso.fechasistema);
//        fecha.setText(acceso.fechasistema);
        txtcodsucursal.setText(acceso.ususucur);
        txtsucurdescri.setText(acceso.sucurdescri);
        txtcodper.setText(acceso.usucod);
        lnombre.setText(acceso.usunom);

        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        //  lfecha.setText(acceso.fechasistema);
        fechas.setText(acceso.fechasistema);
        // txtcodsucursal.setText(acceso.ususucur);
        // txtsucurdescri.setText(acceso.sucurdescri);
        txtcodsucursal.setEnabled(false);
        txtsucurdescri.setEnabled(false);
        txtcodper.setEnabled(false);
        this.setLocationRelativeTo(null);
        //  hab_botones();
        Timer time = new Timer(250, new escucha());
        time.start();
        int c;
        fecha();
    }

    class escucha implements ActionListener {

        public void actionPerformed(ActionEvent e) {
            Calendar ahora = Calendar.getInstance();
            int hor = ahora.get(Calendar.HOUR_OF_DAY);
            int min = ahora.get(Calendar.MINUTE);
            int seg = ahora.get(Calendar.SECOND);
            // hora.setText(hor + ":" + min + ":" + seg);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        turno = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lcodigo = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        lcodigo2 = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        lcodigo3 = new javax.swing.JLabel();
        txtcodsucursal = new javax.swing.JTextField();
        txtsucurdescri = new javax.swing.JTextField();
        txtcodper = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        fechas = new javax.swing.JTextField();
        txthora = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtbarra = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtdescripcion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        grilla1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtbarra1 = new javax.swing.JTextField();
        txtID1 = new javax.swing.JTextField();
        txtdescripcion1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtcantidad1 = new javax.swing.JTextField();
        bagregar = new javax.swing.JButton();
        bgrabar = new javax.swing.JButton();
        bcancelar = new javax.swing.JButton();
        bsalir = new javax.swing.JButton();
        bborrar = new javax.swing.JButton();
        turno1 = new javax.swing.JLabel();
        turno2 = new javax.swing.JLabel();
        bborrar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        turno.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        turno.setText("Gestion de Conversiones");

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lcodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo.setText("Sucursal");

        txtcodigo.setEditable(false);
        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        lcodigo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo2.setText("Codigo :");

        lnombre.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lnombre.setText("Nombre");

        lcodigo3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lcodigo3.setText("Usuario:");

        txtcodsucursal.setEditable(false);
        txtcodsucursal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodsucursalActionPerformed(evt);
            }
        });
        txtcodsucursal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodsucursalKeyTyped(evt);
            }
        });

        txtsucurdescri.setEditable(false);

        txtcodper.setEditable(false);
        txtcodper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodperActionPerformed(evt);
            }
        });
        txtcodper.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcodperKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcodperKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Fecha :");

        fechas.setEditable(false);
        fechas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechasActionPerformed(evt);
            }
        });
        fechas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                fechasKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                fechasKeyTyped(evt);
            }
        });

        txthora.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txthora.setText("HORA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lcodigo2)
                .addGap(8, 8, 8)
                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(lcodigo3)
                .addGap(7, 7, 7)
                .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lnombre)
                .addGap(18, 18, 18)
                .addComponent(lcodigo)
                .addGap(18, 18, 18)
                .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txthora, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lcodigo2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lcodigo)
                        .addComponent(lnombre)
                        .addComponent(lcodigo3)
                        .addComponent(txtcodsucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtsucurdescri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(fechas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txthora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtcodper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Codigo Producto:");

        txtbarra.setEnabled(false);
        txtbarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarraActionPerformed(evt);
            }
        });
        txtbarra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarraKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbarraKeyTyped(evt);
            }
        });

        txtID.setEditable(false);
        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });
        txtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIDKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDKeyTyped(evt);
            }
        });

        txtdescripcion.setEditable(false);
        txtdescripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcionActionPerformed(evt);
            }
        });
        txtdescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcionKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Cantidad :");

        txtcantidad.setEnabled(false);
        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });

        grilla.setBackground(new java.awt.Color(102, 255, 255));
        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Id Producto", "Barra", "Descripcion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla);

        grilla1.setBackground(new java.awt.Color(102, 255, 255));
        grilla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Id Producto", "Barra", "Descripcion", "Cantidad"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(grilla1);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Codigo Producto:");

        txtbarra1.setEnabled(false);
        txtbarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbarra1ActionPerformed(evt);
            }
        });
        txtbarra1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtbarra1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbarra1KeyTyped(evt);
            }
        });

        txtID1.setEditable(false);
        txtID1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtID1ActionPerformed(evt);
            }
        });
        txtID1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtID1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtID1KeyTyped(evt);
            }
        });

        txtdescripcion1.setEditable(false);
        txtdescripcion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdescripcion1ActionPerformed(evt);
            }
        });
        txtdescripcion1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdescripcion1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtdescripcion1KeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Cantidad :");

        txtcantidad1.setEnabled(false);
        txtcantidad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidad1ActionPerformed(evt);
            }
        });
        txtcantidad1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcantidad1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidad1KeyTyped(evt);
            }
        });

        bagregar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bagregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1486485588-add-create-new-math-sign-cross-plus_81186.png"))); // NOI18N
        bagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bagregarActionPerformed(evt);
            }
        });

        bgrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bgrabar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/savedisk_floppydisk_guardar_1543.png"))); // NOI18N
        bgrabar.setEnabled(false);
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });

        bcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancel_icon-icons.com_73703.png"))); // NOI18N
        bcancelar.setEnabled(false);
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout_90894.png"))); // NOI18N
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        bborrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bborrar.setText("Borrar item");
        bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrarActionPerformed(evt);
            }
        });

        turno1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        turno1.setText("Sumar a:");

        turno2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        turno2.setText("Restar de:");

        bborrar1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bborrar1.setText("Borrar item");
        bborrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bagregar)
                .addGap(18, 18, 18)
                .addComponent(bgrabar)
                .addGap(18, 18, 18)
                .addComponent(bcancelar)
                .addGap(18, 18, 18)
                .addComponent(bsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bborrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtbarra1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtdescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(62, 62, 62)
                                    .addComponent(jLabel10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtcantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 928, Short.MAX_VALUE)
                                .addComponent(jScrollPane2))
                            .addComponent(bborrar1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(409, 409, 409)
                        .addComponent(turno1)))
                .addContainerGap(84, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(408, 408, 408)
                    .addComponent(turno2)
                    .addContainerGap(541, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bborrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(turno1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdescripcion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtbarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bborrar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalir)
                    .addComponent(bagregar)
                    .addComponent(bgrabar)
                    .addComponent(bcancelar))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(turno2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(343, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
        // busca_detalle();
        //   beditar.setEnabled(true);
        //    bgrabar.setEnabled(false);
        //    buscarcompras();
        //  txttotal.setEnabled(false);
        //    txtdescripcion.setEnabled(false);
        //  txtmercacod.requestFocus();
        txtcodigo.setEnabled(false);
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void txtcodsucursalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodsucursalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalActionPerformed

    private void txtcodsucursalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyPressed

    private void txtcodsucursalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodsucursalKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodsucursalKeyTyped

    private void txtcodperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodperActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperActionPerformed

    private void txtcodperKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyPressed

    private void txtcodperKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcodperKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodperKeyTyped

    private void fechasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechasActionPerformed
        // TODO add your handling code here:
        //  txtmercacod.requestFocus();
        fechas.setEnabled(false);
        //  bgrabar.setEnabled(true);
        //   bgrabar.requestFocus();
    }//GEN-LAST:event_fechasActionPerformed

    private void fechasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyPressed

    private void fechasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fechasKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_fechasKeyTyped

    private void txtbarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarraActionPerformed
        // TODO add your handling code here:
        buscarArticulo();

    }//GEN-LAST:event_txtbarraActionPerformed

    private void txtbarraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyPressed
        // TODO add your handling code here:
        if (txtbarra.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        {
            JTextField[] tfParam = new JTextField[2];
            tfParam[0] = this.txtbarra;
            VentanaBuscar buscador = new VentanaBuscar("SELECT BARRA,UPPER(descripcion)AS descripcion\n"
                    + "FROM producto where descripcion like  ", new String[]{"CODIGO PRODUCTO", "NOMBRE PRODUCTO"}, 2, tfParam);
            buscador.setTitle("Buscar PRODUCTOS");
            buscador.setVisible(true);
        }
    }//GEN-LAST:event_txtbarraKeyPressed

    private void txtbarraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarraKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarraKeyTyped

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtIDActionPerformed

    private void txtIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyPressed

    private void txtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDKeyTyped

    private void txtdescripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcionActionPerformed
        // TODO add your handling code here:
        //        buscar_cod();
    }//GEN-LAST:event_txtdescripcionActionPerformed

    private void txtdescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyPressed
        // TODO add your handling code here:
        ////        if (txtmercacod.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER) {// presiona F12
        ////            new bus_art(null,true).setVisible(true);// llama al buscador
        ////
        ////            if (bus_art.vdes.isEmpty())//no trae nada
        ////            {
        ////                return;
        ////            }else // trae datos
        ////            {
        ////                txtmercacod.setText(bus_art.vcod);
        ////                txtdescri.setText((bus_art.vdes));
        ////                //  txtprecio.setText(bus_art.vprecio);
        ////                // txttotal.requestFocus();
        ////
        ////            }
        ////        }//fin F12
        ////
        ////        if(evt.getKeyCode()==35) { // presiona TECLA FIN
        ////            bgrabar.setEnabled(true);
        ////            //  bgrabar.requestFocus();
        ////            txtcantidad.setEnabled(true);
        ////            txtcantidad.requestFocus();
        ////        }
        ////        //          if (txtmerca.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        ////        //        {
        ////            //            JTextField[] tfParam = new JTextField[2];
        ////            //            tfParam[0] = this.txtmerca;
        ////            //            tfParam[1] = this.txtdescri;
        ////            //            VentanaBuscar buscador = new VentanaBuscar("select mer_cod,mer_nom from mercaderia where mer_nom like  ", new String[]{"CODIGO marca", "NOMBRE marca ACTIVO"}, 2, tfParam);
        ////            //            buscador.setTitle("Buscar Merca");
        ////            //            buscador.setVisible(true);
        ////            //    }
    }//GEN-LAST:event_txtdescripcionKeyPressed

    private void txtdescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcionKeyTyped
        // TODO add your handling code here:
        char caracter = evt.getKeyChar();
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_txtdescripcionKeyTyped

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
        try {
            String cant;
            cant = txtcantidad.getText();
            int multnum = 0;
            multnum = Integer.parseInt(cant);
            if (multnum <= 0) {
                JOptionPane.showMessageDialog(null, "TIENE QUE SER UN N° POSITIVO Y UN NUMERO MAYOR A CERO ");
                txtcantidad.requestFocus();
            } else {

                tirar_grillas();
                bcancelar.setEnabled(true);
                //bgrabar.setEnabled(true);
                txtbarra1.setEnabled(true);
                txtbarra1.requestFocus();
            }
        } catch (Exception e) {
            // getToolkit().beep();
        }
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyPressed

        if (evt.getKeyCode() == 10) { // presiona ENTER

            ////fin verificacion
            int subtotal;
            //  subtotal = Integer.parseInt(txtcantidad.getText()) * Integer.parseInt(txtprecio.getText());

            //    total = total + subtotal;
            // txttotal.setText(String.valueOf(total));
            //  Total3.setText(String.valueOf(total));
            //      txtletras.setText(numero.nletra(total));
            /////tira a la grilla
        }
    }//GEN-LAST:event_txtcantidadKeyPressed

    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadKeyTyped

    private void txtbarra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbarra1ActionPerformed
        // TODO add your handling code here:
        buscarArticulo2();
    }//GEN-LAST:event_txtbarra1ActionPerformed

    private void txtbarra1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarra1KeyPressed
        // TODO add your handling code here:
              // TODO add your handling code here:
        if (txtbarra1.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        {
            JTextField[] tfParam = new JTextField[2];
            tfParam[0] = this.txtbarra1;
            VentanaBuscar buscador = new VentanaBuscar("SELECT BARRA,UPPER(descripcion)AS descripcion\n"
                    + "FROM producto where descripcion like  ", new String[]{"CODIGO PRODUCTO", "NOMBRE PRODUCTO"}, 2, tfParam);
            buscador.setTitle("Buscar PRODUCTOS");
            buscador.setVisible(true);
        }
    }//GEN-LAST:event_txtbarra1KeyPressed

    private void txtbarra1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbarra1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtbarra1KeyTyped

    private void txtID1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtID1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1ActionPerformed

    private void txtID1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1KeyPressed

    private void txtID1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtID1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtID1KeyTyped

    private void txtdescripcion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdescripcion1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcion1ActionPerformed

    private void txtdescripcion1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcion1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcion1KeyPressed

    private void txtdescripcion1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdescripcion1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdescripcion1KeyTyped

    private void txtcantidad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidad1ActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        try {
            String cant;
            cant = txtcantidad1.getText();
            int multnum = 0;
            multnum = Integer.parseInt(cant);
            if (multnum <= 0) {
                JOptionPane.showMessageDialog(null, "TIENE QUE SER UN N° POSITIVO Y UN NUMERO MAYOR A CERO ");
                txtcantidad1.requestFocus();
            } else {
                for (int fila = 0; fila < grilla.getRowCount(); fila++) {

                    if (grilla.getValueAt(fila, 1).toString().trim().equals(txtID1.getText().trim())) {
                        JOptionPane.showMessageDialog(null, "OPERACION NO REALIZADA, NO SE PUDEN CONVERTIR EL MISMO PRODUCTO.");
                        txtbarra1.requestFocus();
                        txtID1.setText("");
                        txtdescripcion1.setText("");
                        txtcantidad1.setText("");
                        txtcantidad1.setEnabled(false);
                    } else {
                        tirar_grillas2();
                        bgrabar.setEnabled(true);
                    }
                }

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error" + e);
        }
    }//GEN-LAST:event_txtcantidad1ActionPerformed

    private void txtcantidad1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidad1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidad1KeyPressed

    private void txtcantidad1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidad1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidad1KeyTyped

    private void bagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bagregarActionPerformed
        operacion = "agregar";
        gencod();
        mostrar_fecha();
        txtbarra.setEnabled(true);
        txtbarra.requestFocus();
        bagregar.setEnabled(false);
    }//GEN-LAST:event_bagregarActionPerformed

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        // TODO add your handling code here:
        validarfecha();
        grabar();
        bcancelar.setEnabled(false);
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        // TODO add your handling code here:
        limpiargrilla1();
        limpiargrilla2();
        limpiarTextos();
        des_text();
        bgrabar.setEnabled(false);
        bagregar.setEnabled(true);
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_bsalirActionPerformed

    private void bborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrarActionPerformed
        cursor.removeRow(grilla.getSelectedRow());
        txtbarra.setEnabled(true);
        txtbarra.requestFocus();
    }//GEN-LAST:event_bborrarActionPerformed

    private void bborrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrar1ActionPerformed
        // TODO add your handling code here:
        cursor2.removeRow(grilla1.getSelectedRow());
        txtbarra1.setEnabled(true);
        txtbarra1.requestFocus();
    }//GEN-LAST:event_bborrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Conversiones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Conversiones().setVisible(true);
            }
        });
    }
    public String operacion = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bagregar;
    private javax.swing.JButton bborrar;
    private javax.swing.JButton bborrar1;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bsalir;
    private javax.swing.JTextField fechas;
    private javax.swing.JTable grilla;
    private javax.swing.JTable grilla1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lcodigo2;
    private javax.swing.JLabel lcodigo3;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel turno;
    private javax.swing.JLabel turno1;
    private javax.swing.JLabel turno2;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtID1;
    private javax.swing.JTextField txtbarra;
    private javax.swing.JTextField txtbarra1;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcantidad1;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodper;
    private javax.swing.JTextField txtcodsucursal;
    private javax.swing.JTextField txtdescripcion;
    private javax.swing.JTextField txtdescripcion1;
    private javax.swing.JLabel txthora;
    private javax.swing.JTextField txtsucurdescri;
    // End of variables declaration//GEN-END:variables

    private void fecha() {
        try {
            ver_conex conn = new ver_conex();//instanciamos current_date()  (curdate())
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select date_format(current_date(),'%Y/%m/%d') as fecha");
            conn.resultado.next();
            fechas.setText(conn.resultado.getString("fecha"));
            Hora1();

        } catch (SQLException exceptionSql) {
            JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
            // System.exit(0);
        }
    }//fin generar

    private void Hora1() {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select curtime() as hora");
            conn.resultado.next();
            txthora.setText(conn.resultado.getString("hora"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    public void buscarArticulo() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT PRD_COD,DESCRIPCION,BARRA\n"
                    + "FROM PRODUCTO\n"
                    + "WHERE BARRA = " + this.txtbarra.getText());
            if (conn.resultado.next())//si encontro
            {
                this.txtbarra.setText(conn.resultado.getString("BARRA"));
                this.txtID.setText(conn.resultado.getString("PRD_COD"));
                this.txtdescripcion.setText(conn.resultado.getString("DESCRIPCION"));
                txtcantidad.setEnabled(true);
                txtcantidad.requestFocus();
                //   this.txtdepdescri.setText(conn.resultado.getString("depo_desc"));
            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "El codigo ingresado aun no esta Registrado");
                txtbarra.requestFocus();
            }
        } catch (SQLException exceptionSql) {
            //   JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }

    public void buscarArticulo2() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT PRD_COD,DESCRIPCION,BARRA\n"
                    + "FROM PRODUCTO\n"
                    + "WHERE BARRA = " + this.txtbarra1.getText());

            if (conn.resultado.next())//si encontro
            {
                this.txtbarra1.setText(conn.resultado.getString("BARRA"));
                this.txtID1.setText(conn.resultado.getString("PRD_COD"));
                this.txtdescripcion1.setText(conn.resultado.getString("DESCRIPCION"));
                txtcantidad1.setEnabled(true);
                txtcantidad1.requestFocus();
                //   this.txtdepdescri.setText(conn.resultado.getString("depo_desc"));
            } else//no encontro
            {
                JOptionPane.showMessageDialog(null, "El codigo ingresado aun no esta Registrado");
                txtbarra1.requestFocus();
            }

        } catch (SQLException exceptionSql) {
            //   JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "Error de Conexion con la Base de Datos", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tirar_grillas() {
        try {
            do {
                c++;
                DefaultTableModel dt;
                dt = (DefaultTableModel) grilla.getModel();
                String campos[] = new String[]{String.valueOf(c), txtID.getText(), txtbarra.getText(), txtdescripcion.getText(), txtcantidad.getText()};//cantid
                dt.addRow(campos);
            } while (conn.resultado.next());
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        txtcantidad.setEnabled(false);

        txtcantidad.setText("");
        txtdescripcion.setText("");
        txtID.setText("");
        txtbarra.setText("");
        txtbarra.setEnabled(false);
        txtcantidad.setEnabled(false);
    }

    private void tirar_grillas2() {
        try {
            do {
                c++;
                DefaultTableModel dt;
                dt = (DefaultTableModel) grilla1.getModel();
                String campos[] = new String[]{String.valueOf(c1), txtID1.getText(), txtbarra1.getText(), txtdescripcion1.getText(), txtcantidad1.getText()};//cantid
                dt.addRow(campos);
            } while (conn.resultado.next());
        } catch (NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "ERROR" + e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
        }
        txtcantidad1.setEnabled(false);

        txtcantidad1.setText("");
        txtdescripcion1.setText("");
        txtID1.setText("");
        txtbarra1.setText("");
        txtbarra1.setEnabled(false);
        txtcantidad1.setEnabled(false);
    }

    private void limpiargrilla1() {
        for (int i = grilla.getRowCount() - 1; i >= 0; i--) {
            cursor.removeRow(i);
        }
    }

    private void limpiargrilla2() {
        for (int i = grilla1.getRowCount() - 1; i >= 0; i--) {
            cursor2.removeRow(i);
        }
    }

    private void mostrar_fecha() {

        try {
            ver_conex c = new ver_conex();
            c.sentencia = c.conexion.createStatement();
            c.resultado = c.sentencia.executeQuery("select date_format(current_date(),'%d/%m/%Y') as fecha");
            while (c.resultado.next()) {
                fechas.setText(c.resultado.getString("fecha"));
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }

    private void gencod() {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+ 1 AS xxx FROM cabecera_conv");
            conn.resultado.next();
            this.txtcodigo.setText(conn.resultado.getString("xxx"));
        } catch (SQLException ex) {
            Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    private void gencodDetalle() {
        try {

            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(id),0)+1 AS newcod ,CURDATE() AS fecha FROM detalle_conv");
            conn.resultado.next();
            id_detalle = Integer.parseInt(conn.resultado.getString("newcod"));
        } catch (SQLException ex) {
        }
    }

    private void validarfecha() {
        String fecha11 = fechas.getText();
        if (fecha11.equals("")) {
            mensajeValidar(this, "\"FECHA\"");
        }
    }

    private static void mensajeValidar(JFrame x, String campo) {
        JOptionPane.showMessageDialog(x, "El campo " + campo + " no puede estar vacío-cargue y luego guarde! ", "Campos incompletos", JOptionPane.INFORMATION_MESSAGE);
    }

    private void salir() {
        int respuesta = JOptionPane.showConfirmDialog(this, "DESEA SALIR", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            dispose();
        }
    }

    private void limpiarTextos() {
        txtcodigo.setText("");
        txtcodper.setText("");
        txtcodsucursal.setText("");
        txtsucurdescri.setText("");
        fechas.setText("");
        txthora.setText("");

        txtbarra.setText("");
        txtID.setText("");
        txtdescripcion.setText("");
        txtcantidad.setText("");

        txtbarra1.setText("");
        txtID1.setText("");
        txtdescripcion1.setText("");
        txtcantidad1.setText("");

    }

    private void grabar() {
        int res = javax.swing.JOptionPane.showOptionDialog(this,
                "Desea grabar la Conversion?", "Producsys", javax.swing.JOptionPane.OK_CANCEL_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE, null,
                new Object[]{"Si", "No"}, "Si");

        if (res == javax.swing.JOptionPane.OK_OPTION) {

            try {
                ver_conex conn = new ver_conex();
                conn.sentencia = conn.conexion.createStatement();
                gencod();
                conn.sentencia.executeUpdate("INSERT INTO cabecera_conv(id,fecha,hora,usuario) "
                        + "values(" + txtcodigo.getText() + ",'" + fechas.getText() + "','" + txthora.getText() + "'," + txtcodper.getText() + ")");
 
                gencodDetalle();
                //graba en el detalle

                for (int fila = 0; fila < grilla.getRowCount(); fila++) {
                    gencodDetalle();
                    conn.sentencia.executeUpdate("insert into detalle_conv(id,id_cabecera,prd_desde,cant_desde,prd_hasta,cant_hasta)values"
                            + "(" + id_detalle + "," + txtcodigo.getText() + "," + grilla.getValueAt(fila, 1) + "," + grilla.getValueAt(fila, 4) + "," + 0 + "," + 0 + ")");
                }
                for (int fila2 = 0; fila2 < grilla1.getRowCount(); fila2++) {
                    conn.sentencia.executeUpdate("update detalle_conv set prd_hasta ='" + grilla1.getValueAt(fila2, 1) + "' , cant_hasta = '" + grilla1.getValueAt(fila2, 4) + "' WHERE id =" + id_detalle);
                }
                JOptionPane.showMessageDialog(null, "La Conversion fue grabada Satisfactoriamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                limpiargrilla1();
                limpiargrilla2();
                limpiarTextos();

                des_text();
                bgrabar.setEnabled(false);
                bagregar.setEnabled(true);

            } catch (Exception ex) {
                Logger.getLogger(compras.class.getName()).log(Level.SEVERE, null, ex);

            }
        } else {
            JOptionPane.showMessageDialog(null, "Operacion Cancelada", "Atencion", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void des_text() {
        txtbarra.setEnabled(false);
        txtbarra1.setEnabled(false);
        txtcantidad.setEnabled(false);
        txtcantidad1.setEnabled(false);

    }
}
