/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * registrar_transferencia.java
 *
 * Created on 16-nov-2015, 17:50:04
 */

package formularios;

import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import programas.ver_conex;

/**
 *
 * @author CLAU LORE
 */
public class registrar_transferencia extends javax.swing.JFrame {

    /** Creates new form registrar_transferencia */

    ver_conex conn = new ver_conex();
    javax.swing.table.DefaultTableModel cursor;
    String operacion="";
    int c;
    private int band = 0;

    public registrar_transferencia() {
        initComponents();

                this.setLocationRelativeTo(null);
        t_cod_sucursal.setText(acceso.ususucur);//codigo de sucursal
        t_sucursal.setText(acceso.sucurdescri); // sucursal
        t_cod_personal.setText(acceso.usucod);//codigo usuario
        t_nombre.setText(acceso.usunom);    //nombre de usuario
       
        cursor = (javax.swing.table.DefaultTableModel)tabla.getModel();
        setResizable(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t_cod_unidad = new javax.swing.JTextField();
        t_unidad = new javax.swing.JTextField();
        t_cod_producto = new javax.swing.JTextField();
        t_producto = new javax.swing.JTextField();
        t_tipo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        t_presentacion = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_marca = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        t_cantidad = new javax.swing.JTextField();
        t_grupo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        t_deposito = new javax.swing.JTextField();
        t_cod_deposito = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        t_numero_transferencia = new javax.swing.JTextField();
        t_cod_destino = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        t_hora = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        t_destino = new javax.swing.JTextField();
        t_fecha = new javax.swing.JTextField();
        jr_traslado = new javax.swing.JRadioButton();
        jr_envio = new javax.swing.JRadioButton();
        jLabel20 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        t_cod_personal = new javax.swing.JTextField();
        t_nombre = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        t_cod_sucursal = new javax.swing.JTextField();
        t_sucursal = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        b_grabar = new javax.swing.JButton();
        b_anular = new javax.swing.JButton();
        b_editar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();
        b_nuevo = new javax.swing.JButton();
        b_salir = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        b_borrar_items = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "PRODUCTOS", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("PRODUCTO:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("UNIDAD:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("TIPO:");

        t_cod_unidad.setEnabled(false);
        t_cod_unidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cod_unidadActionPerformed(evt);
            }
        });
        t_cod_unidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_cod_unidadKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cod_unidadKeyTyped(evt);
            }
        });

        t_unidad.setEnabled(false);

        t_cod_producto.setEnabled(false);
        t_cod_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cod_productoActionPerformed(evt);
            }
        });
        t_cod_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_cod_productoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cod_productoKeyTyped(evt);
            }
        });

        t_producto.setEnabled(false);

        t_tipo.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("PRESENTACION:");

        t_presentacion.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("MARCA:");

        t_marca.setEnabled(false);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("CANTIDAD:");

        t_cantidad.setEnabled(false);
        t_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cantidadActionPerformed(evt);
            }
        });
        t_cantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cantidadKeyTyped(evt);
            }
        });

        t_grupo.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("GRUPO:");

        t_deposito.setEnabled(false);

        t_cod_deposito.setEnabled(false);
        t_cod_deposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cod_depositoActionPerformed(evt);
            }
        });
        t_cod_deposito.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_cod_depositoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cod_depositoKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("DEPOSITO:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel17.setText("BUSCAR CON F12 ");

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel18.setText("BUSCAR CON F12 ");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel19.setText("BUSCAR CON F12 ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(67, 67, 67)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_cod_producto)
                            .addComponent(t_cod_unidad, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(t_unidad)
                            .addComponent(t_producto, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9)
                            .addComponent(jLabel15)
                            .addComponent(jLabel14)
                            .addComponent(jLabel11))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t_cantidad, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(t_cod_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t_deposito, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addComponent(t_grupo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(t_marca, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(t_presentacion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                            .addComponent(t_tipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t_cod_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel17)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(t_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addComponent(t_cod_unidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(8, 8, 8)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel15))
                    .addComponent(t_cod_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(t_deposito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(t_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_presentacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(t_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(t_grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "DATOS", javax.swing.border.TitledBorder.RIGHT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        t_numero_transferencia.setEnabled(false);
        t_numero_transferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_numero_transferenciaActionPerformed(evt);
            }
        });
        t_numero_transferencia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_numero_transferenciaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_numero_transferenciaKeyTyped(evt);
            }
        });

        t_cod_destino.setEnabled(false);
        t_cod_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_cod_destinoActionPerformed(evt);
            }
        });
        t_cod_destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_cod_destinoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_cod_destinoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("HORA:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("FECHA:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("NUMERO:");

        t_hora.setEnabled(false);
        t_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_horaActionPerformed(evt);
            }
        });
        t_hora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_horaKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DESTINO:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("MOTIVO:");

        t_destino.setEnabled(false);
        t_destino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_destinoActionPerformed(evt);
            }
        });
        t_destino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                t_destinoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t_destinoKeyTyped(evt);
            }
        });

        t_fecha.setEnabled(false);
        t_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_fechaActionPerformed(evt);
            }
        });

        jr_traslado.setText("TRANSLADO");
        jr_traslado.setEnabled(false);
        jr_traslado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_trasladoActionPerformed(evt);
            }
        });

        jr_envio.setText("ENVIO");
        jr_envio.setEnabled(false);
        jr_envio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_envioActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel20.setText("BUSCAR CON F12 ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel16)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(t_cod_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(t_destino))
                    .addComponent(t_hora)
                    .addComponent(t_fecha)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t_numero_transferencia, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jr_traslado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jr_envio))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t_numero_transferencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jr_envio)
                            .addComponent(jr_traslado))
                        .addGap(18, 18, 18)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t_cod_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(65, 65, 65))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));

        t_cod_personal.setEnabled(false);

        t_nombre.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t_nombre.setText("NOMBRE");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("FUNCIONARIO:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("SUCURSAL:");

        t_cod_sucursal.setEnabled(false);

        t_sucursal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        t_sucursal.setText("NOMBRE");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("TRANSFERENCIAS");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(t_cod_personal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(t_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jLabel13)
                .addGap(22, 22, 22)
                .addComponent(t_cod_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(t_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(t_cod_personal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(t_nombre)
                    .addComponent(t_cod_sucursal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(t_sucursal))
                .addContainerGap())
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));

        b_grabar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_grabar.setText("GRABAR");
        b_grabar.setEnabled(false);
        b_grabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_grabarActionPerformed(evt);
            }
        });

        b_anular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_anular.setText("ANULAR");
        b_anular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_anularActionPerformed(evt);
            }
        });

        b_editar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_editar.setText("EDITAR");
        b_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_editarActionPerformed(evt);
            }
        });

        b_cancelar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_cancelar.setText("CANCELAR");
        b_cancelar.setEnabled(false);
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        b_nuevo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_nuevo.setText("NUEVO");
        b_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nuevoActionPerformed(evt);
            }
        });

        b_salir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_salir.setText("SALIR");
        b_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(b_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(b_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(b_anular, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(b_grabar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(b_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_nuevo)
                    .addComponent(b_editar)
                    .addComponent(b_anular)
                    .addComponent(b_grabar)
                    .addComponent(b_cancelar)
                    .addComponent(b_salir))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ITEMS", "CODIGO", "PRODUCTO", "COD UN", "UNIDAD", "TIPO", "PRESENTACION", "MARCA", "GRUPO", "CANTIDAD", "DEPOSITO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        b_borrar_items.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b_borrar_items.setText("BORRAR ITEM");
        b_borrar_items.setEnabled(false);
        b_borrar_items.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrar_itemsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(b_borrar_items)
                .addContainerGap(742, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(b_borrar_items)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_cod_unidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_unidadKeyPressed

        if (t_cod_unidad.getText().equals("") &&evt.getKeyCode()==123) { // presiona F12
            JTextField[] tfParam = new JTextField[2];

            tfParam[0] = this.t_cod_unidad;
            tfParam[1] = this.t_unidad;
            String sql = "SELECT unid_cod,unid_desc FROM unidad_medida WHERE unid_desc LIKE  ";
            Buscador pp = new Buscador(sql , new String[]{"Codigo", "Descripcion"},2, tfParam);
            pp.setTitle("Buscar unidad");
            pp.setVisible(true);
        }   else if (evt.getKeyCode() ==KeyEvent.VK_ENTER  &&   t_cod_unidad.getText().equals("") ){

          JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_cod_unidad.setEnabled(true);
            this.t_cod_unidad.requestFocus();
        }
    }//GEN-LAST:event_t_cod_unidadKeyPressed

    private void t_cod_unidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_unidadKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();

        }
}//GEN-LAST:event_t_cod_unidadKeyTyped

    private void t_cod_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cod_productoActionPerformed

            buscar_producto();
}//GEN-LAST:event_t_cod_productoActionPerformed

    private void t_cod_productoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_productoKeyPressed
        if (t_cod_producto.getText().equals("") &&evt.getKeyCode()==123) { // presiona F12
            JTextField[] tfParam = new JTextField[6];

            tfParam[0] = this.t_cod_producto;
            tfParam[1] = this.t_producto;
            tfParam[2] = this.t_marca;
            tfParam[3] = this.t_presentacion;
            tfParam[4] = this.t_tipo;
            tfParam[5] = this.t_grupo;


            String sql = "SELECT p.prd_cod,p.prd_nom, ma.mar_desc, pe.presen_des,ti.tip_prd_dec,g.grup_descri FROM producto p, tipo_producto ti,marcas ma, presentacion pe,grupo g WHERE g.grup_cod=p.grup_cod AND ma.mar_cod=p.mar_cod AND p.presen_cod=pe.presen_cod AND ti.tip_prd_cod=p.tip_prd_cod AND p.prd_nom LIKE ";
            Buscador pp = new Buscador(sql , new String[]{"Codigo", "Descripcion","Marca","Presentacion","Tipo de Producto","Grupo"},6, tfParam);
            pp.setTitle("Buscar Productos");
            pp.setVisible(true);
        }  else if (evt.getKeyCode() ==KeyEvent.VK_ENTER  &&   t_cod_producto.getText().equals("") ){

          JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_cod_producto.setEnabled(true);
            this.t_cod_producto.requestFocus();
        }
}//GEN-LAST:event_t_cod_productoKeyPressed

    private void t_cod_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_productoKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
}//GEN-LAST:event_t_cod_productoKeyTyped

    private void t_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cantidadActionPerformed
        try {
            String cant;
            cant = t_cantidad.getText();
            int multnum = 0;
            multnum = Integer.parseInt(cant);
            if (multnum <= 0) {
                JOptionPane.showMessageDialog(null, "TIENE QUE SER UN N° POSITIVO Y UN NUMERO MAYOR A CERO");
                t_cantidad.requestFocus();
            } else {
                tirar_grilla();
            }
            } catch (Exception e) {
            getToolkit().beep();
            }
}//GEN-LAST:event_t_cantidadActionPerformed

    private void t_cantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cantidadKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
}//GEN-LAST:event_t_cantidadKeyTyped

    private void b_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_salirActionPerformed
        int mensaje = JOptionPane.showConfirmDialog(this, "¿DESEA SALIR?", "CONFIRMAR", JOptionPane.YES_NO_OPTION);
        if (mensaje == JOptionPane.YES_OPTION) {
            dispose();
        }
}//GEN-LAST:event_b_salirActionPerformed

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        hab_botones();
        des_text();
        clear_text();
}//GEN-LAST:event_b_cancelarActionPerformed

    private void b_grabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_grabarActionPerformed
        validarGrilla();
        limpiar_grilla();
        hab_botones();
        des_text();
        clear_text();
        this.t_numero_transferencia.setEnabled(false);
}//GEN-LAST:event_b_grabarActionPerformed

    private void b_anularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_anularActionPerformed
        operacion="anular";
        this.t_numero_transferencia.setEnabled(true);
        this.t_numero_transferencia.requestFocus();
        des_botones();
}//GEN-LAST:event_b_anularActionPerformed

    private void b_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_editarActionPerformed
        operacion="editar";
        des_botones();
        this.t_numero_transferencia.setEnabled(true);
        this.t_numero_transferencia.requestFocus();
}//GEN-LAST:event_b_editarActionPerformed

    private void b_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nuevoActionPerformed
        // TODO add your handling code here:
        operacion = "nuevo";
        gencodigo();
        des_botones();
        hab_text();
        mostrar_fecha();
        Hora();

}//GEN-LAST:event_b_nuevoActionPerformed

    private void t_numero_transferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_numero_transferenciaActionPerformed
        buscar_detalle_transferencia();
}//GEN-LAST:event_t_numero_transferenciaActionPerformed

    private void t_numero_transferenciaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_transferenciaKeyPressed
        if (t_numero_transferencia.getText().equals("") &&evt.getKeyCode()==123) { // presiona F12
            JTextField[] tfParam = new JTextField[4];

            tfParam[0] = this.t_numero_transferencia;
            tfParam[1] = this.t_fecha;
            tfParam[2] = this.t_hora;
            tfParam[3] = this.t_destino;

            String sql = "SELECT transf_cod,trans_fech,trans_hora,destino,motivo FROM cabecera_transf WHERE trans_estado='pendiente' and motivo LIKE ";
            Buscador pp = new Buscador(sql , new String[]{"NUMERO", "FECHA","HORA","DESTINO","MOTIVO"},5, tfParam);
            pp.setTitle("Buscar Recetas");
            pp.setVisible(true);

            } else if (evt.getKeyCode() ==KeyEvent.VK_ENTER  &&   t_numero_transferencia.getText().equals("") ){

          JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_numero_transferencia.setEnabled(true);
            this.t_numero_transferencia.requestFocus();
        }
}//GEN-LAST:event_t_numero_transferenciaKeyPressed

    private void t_numero_transferenciaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_numero_transferenciaKeyTyped
        char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();
        }
}//GEN-LAST:event_t_numero_transferenciaKeyTyped

    private void t_cod_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cod_destinoActionPerformed

          buscar_sucursal();
       

}//GEN-LAST:event_t_cod_destinoActionPerformed

    private void t_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_horaActionPerformed

        if(t_hora.getText().equals("") ||t_hora.getText().trim().length()==0 ){
            JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);
            this.t_cod_destino.setEnabled(false);
            this.t_hora.setEnabled(true);
            this.t_hora.requestFocus();
        } else{
            this.t_cod_destino.setEnabled(true);
            this.t_cod_destino.requestFocus();
              }

    }//GEN-LAST:event_t_horaActionPerformed

    private void t_horaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_horaKeyTyped
  
}//GEN-LAST:event_t_horaKeyTyped

    private void b_borrar_itemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrar_itemsActionPerformed
        cursor.removeRow(tabla.getSelectedRow());
        this.b_borrar_items.setEnabled(false);
}//GEN-LAST:event_b_borrar_itemsActionPerformed

    private void t_destinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_destinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_destinoActionPerformed

    private void t_destinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_destinoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_destinoKeyPressed

    private void t_destinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_destinoKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_t_destinoKeyTyped

    private void t_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_fechaActionPerformed


       if(t_fecha.getText().equals("") ||t_fecha.getText().trim().length()==0 ){
            JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);
            this.t_hora.setEnabled(false);
            this.t_fecha.setEnabled(true);
            this.t_fecha.requestFocus();
        } else{
          this.t_fecha.setEnabled(false);
          this.t_hora.setEnabled(true);
          this.t_hora.requestFocus();
              }

    }//GEN-LAST:event_t_fechaActionPerformed

    private void t_cod_depositoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_depositoKeyPressed
       if (t_cod_deposito.getText().equals("") &&evt.getKeyCode()==123) { // presiona F12
            JTextField[] tfParam = new JTextField[2];

            tfParam[0] = this.t_cod_deposito;
            tfParam[1] = this.t_deposito;
            String sql = "SELECT depo_cod,depo_desc FROM deposito WHERE depo_desc LIKE";
            Buscador pp = new Buscador(sql , new String[]{"Codigo", "Descripcion"},2, tfParam);
            pp.setTitle("Buscar deposito");
            pp.setVisible(true);
        } else if (evt.getKeyCode() ==KeyEvent.VK_ENTER  &&   t_cod_deposito.getText().equals("") ){

          JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_cod_deposito.setEnabled(true);
            this.t_cod_deposito.requestFocus();
        }
    }//GEN-LAST:event_t_cod_depositoKeyPressed

    private void t_cod_depositoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_depositoKeyTyped
            char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();

        }
    }//GEN-LAST:event_t_cod_depositoKeyTyped
String op="";
    private void jr_trasladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_trasladoActionPerformed
      op="jradioT";
      this.t_fecha.setEnabled(true);
      this.t_fecha.requestFocus();
      mostrar_fecha();
     jr_traslado.setSelected(true);
     jr_envio.setSelected(false);


    }//GEN-LAST:event_jr_trasladoActionPerformed

    private void jr_envioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_envioActionPerformed

     op="jradioE";
     this.t_fecha.setEnabled(true);
     this.t_fecha.requestFocus();
     mostrar_fecha();
     jr_traslado.setSelected(false);
     jr_envio.setSelected(true);

    }//GEN-LAST:event_jr_envioActionPerformed

    private void t_cod_destinoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_destinoKeyTyped
         char caracter = evt.getKeyChar();
        if(((caracter < '0') ||
                (caracter > '9')) &&
                (caracter != evt.VK_BACK_SPACE)) {
            evt.consume();

        }
    }//GEN-LAST:event_t_cod_destinoKeyTyped

    private void t_cod_destinoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t_cod_destinoKeyPressed
           if (t_cod_destino.getText().equals("") && evt.getKeyCode()==123) { // presiona F12
            JTextField[] tfParam = new JTextField[2];

            tfParam[0] = this.t_cod_destino;
            tfParam[1] = this.t_destino;
            String sql = "SELECT suc_cod,suc_desc FROM sucursal WHERE suc_desc LIKE";
            Buscador pp = new Buscador(sql , new String[]{"Codigo", "Sucursal"},2, tfParam);
            pp.setTitle("Buscar Destino");
            pp.setVisible(true);
        } else if (evt.getKeyCode() ==KeyEvent.VK_ENTER  &&   t_cod_destino.getText().equals("") ){
          JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_cod_destino.setEnabled(true);
            this.t_cod_destino.requestFocus();
        }
    }//GEN-LAST:event_t_cod_destinoKeyPressed

    private void t_cod_unidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cod_unidadActionPerformed
      buscar_unidad();
    }//GEN-LAST:event_t_cod_unidadActionPerformed

    private void t_cod_depositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_cod_depositoActionPerformed
     buscar_deposito();
    }//GEN-LAST:event_t_cod_depositoActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrar_transferencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_anular;
    private javax.swing.JButton b_borrar_items;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_editar;
    private javax.swing.JButton b_grabar;
    private javax.swing.JButton b_nuevo;
    private javax.swing.JButton b_salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton jr_envio;
    private javax.swing.JRadioButton jr_traslado;
    private javax.swing.JTextField t_cantidad;
    private javax.swing.JTextField t_cod_deposito;
    private javax.swing.JTextField t_cod_destino;
    private javax.swing.JTextField t_cod_personal;
    private javax.swing.JTextField t_cod_producto;
    private javax.swing.JTextField t_cod_sucursal;
    private javax.swing.JTextField t_cod_unidad;
    private javax.swing.JTextField t_deposito;
    private javax.swing.JTextField t_destino;
    private javax.swing.JTextField t_fecha;
    private javax.swing.JTextField t_grupo;
    private javax.swing.JTextField t_hora;
    private javax.swing.JTextField t_marca;
    private javax.swing.JLabel t_nombre;
    private javax.swing.JTextField t_numero_transferencia;
    private javax.swing.JTextField t_presentacion;
    private javax.swing.JTextField t_producto;
    private javax.swing.JLabel t_sucursal;
    private javax.swing.JTextField t_tipo;
    private javax.swing.JTextField t_unidad;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables

     private void des_botones()
   {
      this.b_nuevo.setEnabled(false);
      this.b_anular.setEnabled(false);
      this.b_editar.setEnabled(false);
      this.b_salir.setEnabled(false);
      this.b_cancelar.setEnabled(true);
      this.b_grabar.setEnabled(false);

   }
  private void hab_text()
   {
      this.jr_traslado.setEnabled(true);
      this.jr_envio.setEnabled(true);
   }
  private void hab_botones()
   {
      this.b_nuevo.setEnabled(true);
      this.b_anular.setEnabled(true);
      this.b_salir.setEnabled(true);
      this.b_cancelar.setEnabled(false);
      this.b_grabar.setEnabled(false);
      this.b_editar.setEnabled(true);
       jr_traslado.setSelected(false);
       jr_envio.setSelected(false);

   }
  private void des_text()
   {
     this.t_destino.setEnabled(false);
     this.t_cod_destino.setEnabled(false);
     this.t_numero_transferencia.setEnabled(false);
     this.t_fecha.setEnabled(false);
     this.t_hora.setEnabled(false);
     this.t_cod_producto.setEnabled(false);
     this.t_producto.setEnabled(false);
     this.t_marca.setEnabled(false);
     this.t_tipo.setEnabled(false);
     this.t_presentacion.setEnabled(false);
     this.t_cod_unidad.setEnabled(false);
     this.t_unidad.setEnabled(false);
     this.t_cantidad.setEnabled(false);
     this.t_grupo.setEnabled(false);
     this.t_deposito.setEnabled(false);
     this.t_cod_deposito.setEnabled(false);
     jr_traslado.setEnabled(false);
     jr_envio.setEnabled(false);

   }

    private void clear_text()
   {
       this.t_numero_transferencia.setText("");
       this.t_hora.setText("");
       this.t_destino.setText("");
       this.t_cod_destino.setText("");
       this.t_cod_deposito.setText("");
       this.t_deposito.setText("");
       this.t_fecha.setText("");
       this.t_cantidad.setText("");
       this.t_unidad.setText("");
       this.t_cod_unidad.setText("");
       this.t_cod_producto.setText("");
       this.t_producto.setText("");
       this.t_tipo.setText("");
       this.t_marca.setText("");
       this.t_presentacion.setText("");
       this.t_grupo.setText("");
       jr_traslado.setSelected(false);
       jr_envio.setSelected(false);
       limpiar_grilla();
   }
  private void limpiar_grilla()
   {
   DefaultTableModel dt;
   dt = (DefaultTableModel) tabla.getModel();
   while (tabla.getRowCount() > 0) {
   dt.removeRow(0);
   }
   }


     private void gencodigo(){
   try {
    conn.sentencia = conn.conexion.createStatement();
    conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(transf_cod),0)+1 AS newcod FROM cabecera_transf");
    conn.resultado.next();
    t_numero_transferencia.setText(conn.resultado.getString("newcod"));
         } catch (SQLException ex) {
            Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
         }
         }
         private void mostrar_fecha() {
        try {
        ver_conex c=new ver_conex();
        c.sentencia=c.conexion.createStatement();
        c.resultado=c.sentencia.executeQuery("select date_format(current_date(),'%d/%m/%Y') as fecha");
        while (c.resultado.next()) {
        t_fecha.setText(c.resultado.getString("fecha"));
            }
            } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex.getMessage());
            }
            }
  private void Hora() {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("select curtime() as hora");
            conn.resultado.next();
            t_hora.setText(conn.resultado.getString("hora"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error" + e, "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
        }
private void buscar_sucursal() {
try
{
conn.sentencia = conn.conexion.createStatement();
conn.resultado = conn.sentencia.executeQuery("SELECT suc_cod,suc_desc FROM sucursal WHERE suc_cod ="+this.t_cod_destino.getText());

        if(conn.resultado.next())//si encontro
        {
          this.t_cod_destino.setText(conn.resultado.getString("suc_cod"));
          this.t_destino.setText(conn.resultado.getString("suc_desc"));

          this.t_cod_producto.setEnabled(true);
          this.t_cod_producto.requestFocus();
       

    if(t_cod_destino.getText().equals("") ||t_cod_destino.getText().trim().length()==0 ){
        JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);

            this.t_cod_destino.setEnabled(true);
            this.t_cod_destino.requestFocus();
       }
 }
       else//no encontro
        {
        JOptionPane.showMessageDialog(null,"NO EXISTE LA SUCURSAL", "MENSAJE",
        JOptionPane.INFORMATION_MESSAGE);
        this.t_cod_producto.setEnabled(false);
        this.t_cod_destino.setEnabled(true);
        this.t_cod_destino.requestFocus();
        }
 	}
	catch (SQLException exceptionSql)
	{
	//JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "no debe esta vacio", JOptionPane.ERROR_MESSAGE);
	}
        }

private void buscar_producto() {
try
{
conn.sentencia = conn.conexion.createStatement();
conn.resultado = conn.sentencia.executeQuery("SELECT p.prd_cod,p.prd_nom, ma.mar_desc,g.grup_descri, pe.presen_des,ti.tip_prd_dec FROM grupo g,producto p, tipo_producto ti,marcas ma, presentacion pe WHERE g.grup_cod=p.grup_cod AND  ma.mar_cod=p.mar_cod AND p.presen_cod=pe.presen_cod AND ti.tip_prd_cod=p.tip_prd_cod AND p.prd_cod="+this.t_cod_producto.getText());

        if(conn.resultado.next())//si encontro
        {
          this.t_cod_producto.setText(conn.resultado.getString("prd_cod"));
          this.t_producto.setText(conn.resultado.getString("prd_nom"));
          this.t_marca.setText(conn.resultado.getString("mar_desc"));
          this.t_presentacion.setText(conn.resultado.getString("presen_des"));
          this.t_tipo.setText(conn.resultado.getString("tip_prd_dec"));
          this.t_grupo.setText(conn.resultado.getString("grup_descri"));
          this.t_cod_unidad.setEnabled(true);
          this.t_cod_unidad.requestFocus();
     
      if(t_cod_producto.getText().equals("") ||t_cod_producto.getText().trim().length()==0 ){
        JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);
         this.t_cod_producto.setEnabled(true);
         this.t_cod_producto.requestFocus();
        }
   }
       else//no encontro
        {
     JOptionPane.showMessageDialog(null,"NO EXISTE EL PRODUCTO", "MENSAJE",
     JOptionPane.INFORMATION_MESSAGE);
      this.t_cod_producto.setEnabled(true);
      this.t_cod_producto.requestFocus();
        }
 	}
	catch (SQLException exceptionSql)
	{
//	JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "no debe esta vacio", JOptionPane.ERROR_MESSAGE);
	}
        }
private void buscar_unidad() {
try
{
conn.sentencia = conn.conexion.createStatement();
conn.resultado = conn.sentencia.executeQuery("SELECT unid_cod,unid_desc FROM unidad_medida WHERE unid_cod="+this.t_cod_unidad.getText());

        if(conn.resultado.next())//si encontro
        {
          this.t_cod_unidad.setText(conn.resultado.getString("unid_cod"));
          this.t_unidad.setText(conn.resultado.getString("unid_desc"));

          this.t_cod_deposito.setEnabled(true);
          this.t_cod_deposito.requestFocus();
       
      if(t_cod_unidad.getText().equals("") ||t_cod_unidad.getText().trim().length()==0 ){
        JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);
         this.t_cod_unidad.setEnabled(true);
         this.t_cod_unidad.requestFocus();
        }
           }
       else//no encontro
        {
        JOptionPane.showMessageDialog(null,"NO EXISTE LA UNIDAD DE MEDIDA", "MENSAJE",
        JOptionPane.INFORMATION_MESSAGE);
        this.t_cod_unidad.setEnabled(true);
        this.t_cod_unidad.requestFocus();
        }
 	}
	catch (SQLException exceptionSql)
	{
//	JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "no debe esta vacio", JOptionPane.ERROR_MESSAGE);
	}
        }

private void buscar_deposito() {
try
{
conn.sentencia = conn.conexion.createStatement();
conn.resultado = conn.sentencia.executeQuery("SELECT depo_cod,depo_desc FROM deposito WHERE depo_cod="+this.t_cod_deposito.getText());

        if(conn.resultado.next())//si encontro
        {
          this.t_cod_deposito.setText(conn.resultado.getString("depo_cod"));
          this.t_deposito.setText(conn.resultado.getString("depo_desc"));

          this.t_cantidad.setEnabled(true);
          this.t_cantidad.requestFocus();
        
   if(t_cod_deposito.getText().equals("") ||t_cod_deposito.getText().trim().length()==0 ){
        JOptionPane.showMessageDialog(null,"EL CAMPO NO PUEDE ESTAR VACIO","AVISO",JOptionPane.ERROR_MESSAGE);
         this.t_cod_deposito.setEnabled(true);
         this.t_cod_deposito.requestFocus();
        }
          }
       else//no encontro
        {
        JOptionPane.showMessageDialog(null,"NO EXISTE EL DEPOSITO", "MENSAJE",
        JOptionPane.INFORMATION_MESSAGE);
        this.t_cod_deposito.setEnabled(true);
        this.t_cod_deposito.requestFocus();
        }
 	}
	catch (SQLException exceptionSql)
	{
//	JOptionPane.showMessageDialog(null, exceptionSql.getMessage(), "no debe esta vacio", JOptionPane.ERROR_MESSAGE);
	}
        }


private void buscar_detalle_transferencia(){

try{

     conn.sentencia = conn.conexion.createStatement();
     conn.resultado = conn.sentencia.executeQuery("SELECT * FROM cabecera_transf WHERE  trans_estado='pendiente' AND motivo IN ('por traslado','por envio') AND  transf_cod=" + t_numero_transferencia.getText());
     boolean encontro = conn.resultado.next();
     if (encontro==true)//encontrog
            {
        this.t_numero_transferencia.setText(conn.resultado.getString("transf_cod"));
        this.t_fecha.setText(conn.resultado.getString("trans_fech"));
        this.t_hora.setText(conn.resultado.getString("trans_hora"));
        this.t_destino.setText(conn.resultado.getString("destino"));

         //////////////////////////////////////////////////////

             if (conn.resultado.getString("motivo").equals("por traslado"))//encontrog
                {
            jr_traslado.setSelected(true);
            jr_traslado.setEnabled(false);
            jr_envio.setEnabled(false);
             }
             if (conn.resultado.getString("motivo").equals("por envio"))//encontrog
             {
            jr_envio.setSelected(true);
            jr_traslado.setEnabled(false);
            jr_envio.setEnabled(false);
             }

////////////////////////////////////////////////////////////////////////
           ver_conex conn = new ver_conex();
           conn.sentencia = conn.conexion.createStatement();
           conn.resultado = conn.sentencia.executeQuery("SELECT d.det_item,d.prd_cod,po.prd_nom,d.unid_cod,u.unid_desc,ti.tip_prd_dec,pe.presen_des,ma.mar_desc,g.grup_descri,d.cant_trans,d.depo_cod  FROM  detalle_trasnf d, producto po,presentacion pe,tipo_producto ti, marcas ma, grupo g,unidad_medida u WHERE po.prd_cod=d.prd_cod AND po.presen_cod=pe.presen_cod AND ti.tip_prd_cod=po.tip_prd_cod AND ma.mar_cod=po.mar_cod AND g.grup_cod=po.grup_cod AND u.unid_cod=d.unid_cod AND d.transf_cod="+t_numero_transferencia.getText()); //OJO LE PASO LA SENTENCIA=" + t_numero_receta.getText());
          while(conn.resultado.next())
           {
           conn.sentencia = conn.conexion.createStatement();
           String registro[] = new String[] {conn.resultado.getString("det_item"),conn.resultado.getString("prd_cod"),conn.resultado.getString("prd_nom"),conn.resultado.getString("unid_cod"),conn.resultado.getString("unid_desc"),conn.resultado.getString("tip_prd_dec"),conn.resultado.getString("presen_des"),conn.resultado.getString("mar_desc"),conn.resultado.getString("grup_descri"),conn.resultado.getString("cant_trans"),conn.resultado.getString("depo_cod")};
           cursor.addRow(registro);
           }

        if(operacion.equals("editar")){
        this.t_numero_transferencia.setEnabled(false) ;
        this.t_fecha.setEnabled(true) ;
        this.t_fecha.requestFocus();
              }

        if(operacion.equals("anular")){
        this.t_numero_transferencia.setEnabled(false) ;
        this.b_grabar.setEnabled(true);
        this.b_grabar.requestFocus();

               }
               }
          else{
     JOptionPane.showMessageDialog(null, "NO EXISTE LA TRANSFERENCIA CON ESTE NUMERO", "ATENCION", JOptionPane.ERROR_MESSAGE);
     this.t_numero_transferencia.setEnabled(true);
     this.t_numero_transferencia.requestFocus();
         }
                     ver_conex conn2 = new ver_conex();
                     conn2.sentencia = conn2.conexion.createStatement();
                     conn2.resultado = conn2.sentencia.executeQuery("SELECT * FROM cabecera_transf WHERE  trans_estado='Anulado' AND  transf_cod=" + t_numero_transferencia.getText());
                     boolean encontro3 = conn2.resultado.next();
                    if (encontro3==true)//encontrog
                    {
                    JOptionPane.showMessageDialog(null, "ESTA TRANFERENCIA ESTA ANULADA", "ATENCION", JOptionPane.ERROR_MESSAGE);
                    this.t_numero_transferencia.setEnabled(true);
                    this.t_numero_transferencia.requestFocus();
                   }
//     else{
//     JOptionPane.showMessageDialog(null, "NO EXISTE LA TRANSFERENCIA CON ESTE NUMERO", "ATENCION", JOptionPane.ERROR_MESSAGE);
//     this.t_numero_transferencia.setEnabled(true);
//     this.t_numero_transferencia.requestFocus();
//         }

 } catch(SQLException e){
 //JOptionPane.showMessageDialog(null,e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
  
 }

//try{
//
//                     ver_conex conn2 = new ver_conex();
//                     conn2.sentencia = conn2.conexion.createStatement();
//                     conn2.resultado = conn2.sentencia.executeQuery("SELECT * FROM cabecera_transf WHERE  trans_estado='Anulado' AND  transf_cod=" + t_numero_transferencia.getText());
//                     boolean encontro3 = conn2.resultado.next();
//                    if (encontro3==true)//encontrog
//                    {
//                    JOptionPane.showMessageDialog(null, "ESTA TRANFERENCIA ESTA ANULADA", "ATENCION", JOptionPane.ERROR_MESSAGE);
//                    this.t_numero_transferencia.setEnabled(true);
//                    this.t_numero_transferencia.requestFocus();
//                   }
//}
//
//catch(SQLException ex){
// JOptionPane.showMessageDialog(null,ex.getMessage(), "ERROR DE CONEXION", JOptionPane.ERROR_MESSAGE);
// }

}

private void tirar_grilla() {
try {
   do{
   c++;
      DefaultTableModel dt;
      dt = (DefaultTableModel) tabla.getModel();
      String campos[] = new String[]{String.valueOf(c),t_cod_producto.getText(), t_producto.getText(), t_cod_unidad.getText(), t_unidad.getText(), t_tipo.getText(), t_presentacion.getText(), t_marca.getText(), t_grupo.getText(), t_cantidad.getText(), t_cod_deposito.getText()};
      dt.addRow(campos);
   }while(conn.resultado.next());
   } catch (Exception e) {
   JOptionPane.showMessageDialog(this, "ERROR" + e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
   }
          t_cantidad.setEnabled(false);
          t_cod_unidad.setEnabled(false);
          t_cod_deposito.setEnabled(false);
          t_cantidad.setText("");
          t_cod_producto.setText("");
          t_producto.setText("");
          t_marca.setText("");
          t_tipo.setText("");
          t_presentacion.setText("");
          t_cod_unidad.setText("");
          t_unidad.setText("");
          t_grupo.setText("");
          t_cod_deposito.setText("");
          t_deposito.setText("");
          t_cod_producto.setEnabled(true);
          t_cod_producto.requestFocus();
          b_grabar.setEnabled(true);

     }

private void validarGrilla(){
    int tabla2= tabla.getRowCount();
    if(tabla2==0)
    {
       JOptionPane.showMessageDialog(null,"CARGAR GRILLA PARA CONTINUAR","AVISO",JOptionPane.INFORMATION_MESSAGE);
       t_numero_transferencia.requestFocus();
    }
    else
    {
      grabar();
    }
    }
private void grabar()
{
    try
    {

String f=t_fecha.getText();
String dd=f.substring(0,2);
String mm=f.substring(3,5);
String aa=f.substring(6,10);
String fech=aa+"/"+mm+"/"+dd;
DateFormat df=new SimpleDateFormat(fech);
String SQL = null;

        if(op.equals("jradioT"))
      {
      {
      SQL = "INSERT INTO cabecera_transf VALUES ("+t_numero_transferencia.getText()+","+t_cod_sucursal.getText()+",'"+fech+"','"+t_hora.getText()+"','"+t_destino.getText()+"','por traslado',"+t_cod_personal.getText()+",'pendiente')";

      }
        ver_conex c= new ver_conex();
        c.sentencia= c.conexion.createStatement();
        c.sentencia.executeUpdate(SQL);

        for (int fila = 0; fila < tabla.getRowCount(); fila++)
        {
        c.sentencia = c.conexion.createStatement();
        c.sentencia.executeUpdate("INSERT INTO detalle_trasnf(transf_cod,prd_cod,cant_trans,depo_cod,det_item,unid_cod) VALUES ("+t_numero_transferencia.getText()+","+tabla.getValueAt(fila,1)+","+tabla.getValueAt(fila,9)+","+tabla.getValueAt(fila,10)+","+tabla.getValueAt(fila,0)+","+tabla.getValueAt(fila,3)+")");
        }
    suma_stock();
    JOptionPane.showMessageDialog(this,"LA TRANSFERENCIA FUE  REALIZADA","OPERACION",JOptionPane.INFORMATION_MESSAGE);
    genreporte();

     }
if(op.equals("jradioE"))
      {
      {
      SQL = "INSERT INTO cabecera_transf VALUES ("+t_numero_transferencia.getText()+","+t_cod_sucursal.getText()+",'"+fech+"','"+t_hora.getText()+"','"+t_destino.getText()+"','por envio',"+t_cod_personal.getText()+",'pendiente')";

      }
        ver_conex c= new ver_conex();
        c.sentencia= c.conexion.createStatement();
        c.sentencia.executeUpdate(SQL);

        for (int fila = 0; fila < tabla.getRowCount(); fila++)
        {
        c.sentencia = c.conexion.createStatement();
        c.sentencia.executeUpdate("INSERT INTO detalle_trasnf(transf_cod,prd_cod,cant_trans,depo_cod,det_item,unid_cod) VALUES ("+t_numero_transferencia.getText()+","+tabla.getValueAt(fila,1)+","+tabla.getValueAt(fila,9)+","+tabla.getValueAt(fila,10)+","+tabla.getValueAt(fila,0)+","+tabla.getValueAt(fila,3)+")");

        }
           restar_stock();
           JOptionPane.showMessageDialog(this,"LA TRANSFERENCIA FUE REALIZADA","OPERACION",JOptionPane.INFORMATION_MESSAGE);
           genreporte();
       }
       }
    catch(Exception e)
    {
    }
    try{
    if(operacion.equals("anular"))
    {
    anular();
    }
    if (operacion.equals("editar"))
    {
     editar();
    }
    }
    catch(Exception e)
    {
        JOptionPane.showMessageDialog(this,"ERROR DE CONEXION33"+e,"AVISO",JOptionPane.INFORMATION_MESSAGE);
    }
    }


//////////suma de stock/////////////

private void suma_stock(){
  int cantida=0;
  try {
       for(int fila=0;fila < tabla.getRowCount();fila++){
       ver_conex c= new ver_conex();
       c.sentencia= c.conexion.createStatement();
       c.resultado = c.sentencia.executeQuery("SELECT * FROM stock WHERE depo_cod="+tabla.getValueAt(fila,10)+" and prd_cod="+tabla.getValueAt(fila,1));
       if (c.resultado.next()){
       cantida=c.resultado.getInt("stock_cant");
       c.sentencia.executeUpdate("UPDATE stock SET stock_cant="+cantida+"+"+tabla.getValueAt(fila,9)+" WHERE depo_cod="+tabla.getValueAt(fila,10)+" and prd_cod="+tabla.getValueAt(fila,1));
     }
     }
     } catch (SQLException ex)
     {
     }
     }

//////////resta de stock/////////////

private void restar_stock(){
     int cantida=0;
try {
       for(int fila=0;fila < tabla.getRowCount();fila++){
       ver_conex c= new ver_conex();
       c.sentencia= c.conexion.createStatement();
       c.resultado = c.sentencia.executeQuery("SELECT * FROM stock WHERE depo_cod="+tabla.getValueAt(fila,10)+" and prd_cod="+tabla.getValueAt(fila,1));
       if (c.resultado.next()){
       cantida=c.resultado.getInt("stock_cant");
       c.sentencia.executeUpdate("UPDATE stock SET stock_cant="+cantida+"-"+tabla.getValueAt(fila,9)+" WHERE depo_cod="+tabla.getValueAt(fila,10)+" and prd_cod="+tabla.getValueAt(fila,1));
     }
     }
     } catch (SQLException ex)
     {
     }
     }




public void genreporte() //throws JRException, Exception
    {
        try //throws JRException, Exception
        {
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT t.transf_cod,t.trans_fech,d.prd_cod,t.trans_hora,t.destino,t.tipo_trans,su.suc_desc,po.prd_nom,u.unid_desc,ti.tip_prd_dec,pe.presen_des,ma.mar_desc,g.grup_descri,d.cant_trans,d.depo_cod FROM cabecera_transf t,sucursal su, detalle_trasnf d, producto po,presentacion pe,tipo_producto ti, marcas ma, grupo g,unidad_medida u  WHERE su.suc_cod=t.suc_cod AND d.transf_cod=t.transf_cod AND po.prd_cod=d.prd_cod AND po.presen_cod=pe.presen_cod AND ti.tip_prd_cod=po.tip_prd_cod AND ma.mar_cod=po.mar_cod AND g.grup_cod=po.grup_cod AND u.unid_cod=d.unid_cod AND d.transf_cod="+t_numero_transferencia.getText()); //OJO LE PASO LA SENTENCIA
            JRResultSetDataSource jrRS = new JRResultSetDataSource(conn.resultado);

            HashMap parameters = new HashMap();
            URL urlMaestro = getClass().getClassLoader().getResource("impresion/transferencia.jasper");

            // Cargamos el reporte
            JasperReport masterReport = null;
            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
            JasperPrint masterPrint = null;
            masterPrint = JasperFillManager.fillReport(masterReport, parameters, jrRS);
            JasperViewer ventana = new JasperViewer(masterPrint, false);
            ventana.setTitle("VISTA PREVIA");
            ventana.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

private void anular()
{
  int res = javax.swing.JOptionPane.showOptionDialog(this,
  "DESEA ANULAR LA TRANSFERENCIA?","REGISTRO DE TRANSFERENCIA",javax.swing.JOptionPane.OK_CANCEL_OPTION,
   javax.swing.JOptionPane.QUESTION_MESSAGE,null,
   new Object[] { "Si", "No"},"Si");
     if (res == javax.swing.JOptionPane.OK_OPTION)
        {
    try {
        ver_conex conn= new ver_conex();
        conn.sentencia = conn.conexion.createStatement();
        conn.sentencia.executeUpdate("UPDATE cabecera_transf SET trans_estado='Anulado' WHERE transf_cod = " + t_numero_transferencia.getText());

        JOptionPane.showMessageDialog(null, "LA TRANSFERENCIA FUE ANULADA", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        restar_stock();
        }catch (SQLException ex) {
        Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
        } else
        {
        JOptionPane.showMessageDialog(null, "OPERACIÓN CANCELADA", "ATENCION", JOptionPane.ERROR_MESSAGE);
        }
        limpiar_grilla();
        hab_botones();
        des_text();
        clear_text();
        }


private void editar()
{
try {

ver_conex co= new ver_conex();
co.sentencia = co.conexion.createStatement();
co.sentencia.executeUpdate("UPDATE cabecera_transf SET trans_fech= '"+ t_fecha.getText()+ "',trans_hora= '"+ t_hora.getText()+ "',destino= '"+ t_destino.getText()+ "' WHERE transf_cod = " + t_numero_transferencia.getText());
}catch (SQLException ex) {
 Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
        }
       try {
            ver_conex conn2= new ver_conex();
            conn2.sentencia = conn2.conexion.createStatement();
            String consultaSQL=("SELECT * FROM detalle_trasnf  WHERE  transf_cod= " +t_numero_transferencia.getText());
            conn2.resultado = conn2.sentencia.executeQuery(consultaSQL);


            while (conn2.resultado.next())
{
conn2.sentencia = conn2.conexion.createStatement();
}
conn2.sentencia = conn2.conexion.createStatement();


for (int a = 0; a < tabla.getRowCount(); a++)
{
 String insercionSQLb="DELETE FROM detalle_trasnf WHERE transf_cod = "+t_numero_transferencia.getText ()+" AND prd_cod= "+tabla.getValueAt(a,1)+" AND depo_cod= "+tabla.getValueAt(a,10)+"";
 conn2.sentencia.executeUpdate(insercionSQLb);



Object codigo = tabla.getValueAt(a, 1);
Object cantidad = tabla.getValueAt(a,9);
Object items = tabla.getValueAt(a,0);
Object deposito = tabla.getValueAt(a,10);
Object unidad = tabla.getValueAt(a,3);

conn2.sentencia.executeUpdate("INSERT INTO detalle_trasnf(transf_cod,prd_cod,cant_trans,depo_cod,det_item,unid_cod) VALUES ("+ t_numero_transferencia.getText() +","+ codigo +"," + cantidad + "," + deposito + ","+items + ","+unidad + ")");

}//fin grabacion en detalle

JOptionPane.showMessageDialog(null, "SE HA MODIFICADO LA TRANSFERENCIA", "AVISO",
JOptionPane.INFORMATION_MESSAGE);
genreporte();
 }catch (SQLException ex) {
 Logger.getLogger(registrar_transferencia.class.getName()).log(Level.SEVERE, null, ex);
 }
        limpiar_grilla();
        hab_botones();
        des_text();
        clear_text();
}




}
