package formularios;

import java.sql.ResultSet;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import programas.ver_conex;
import java.nio.file.*;

/**
 *
 * @author eavila
 */
public class ReporteInventario extends javax.swing.JFrame {

    public ResultSet rs;
    private java.sql.ResultSet rss;

    final String nombreArchivoInventario = "\\reportes2\\Inventario.jasper";
    Path rutaRelativaInventario = Paths.get(nombreArchivoInventario);
    Path rutaAbsolutaInventario = rutaRelativaInventario.toAbsolutePath();

    final String NombreArchivoMovCajas = "ReporteMovCajas.jasper";
    Path rutaRelativaMovCajas = Paths.get(NombreArchivoMovCajas);
    Path rutaAbsolutaMovCajas = rutaRelativaMovCajas.toAbsolutePath();

    final String NombreArchivoVentas = "ReporteVentas.jasper";
    Path rutaRelativaVentas = Paths.get(NombreArchivoVentas);
    Path rutaAbsolutaVentas = rutaRelativaVentas.toAbsolutePath();

    /**
     * Creates new form ReporteInventario
     */
    public ReporteInventario() {
        initComponents();
        ver_conex conn = new ver_conex();
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBgenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tdesde = new javax.swing.JFormattedTextField();
        thasta = new javax.swing.JFormattedTextField();
        fhasta = new javax.swing.JFormattedTextField();
        fdesde = new javax.swing.JFormattedTextField();
        rbTodos = new javax.swing.JRadioButton();
        rbMenor10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jr_fecha = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        radioInventario = new javax.swing.JRadioButton();
        radioVentas = new javax.swing.JRadioButton();
        radioCajas = new javax.swing.JRadioButton();
        radioCompras = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(173, 216, 230));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(0, 102, 102));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setText("INFORMES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
        );

        jBgenerar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search_locate_find_icon-icons.com_67287.png"))); // NOI18N
        jBgenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBgenerarActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "ingrese parametros", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel2.setText("Hasta");

        jLabel3.setText("Desde");

        try {
            tdesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tdesde.setEnabled(false);
        tdesde.setFocusAccelerator('-');
        tdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdesdeActionPerformed(evt);
            }
        });

        try {
            thasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        thasta.setEnabled(false);
        thasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thastaActionPerformed(evt);
            }
        });

        try {
            fhasta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fhasta.setEnabled(false);
        fhasta.setFocusAccelerator('-');
        fhasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fhastaActionPerformed(evt);
            }
        });

        try {
            fdesde.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        fdesde.setText("  :  :  :  ");
        fdesde.setEnabled(false);
        fdesde.setFocusAccelerator('-');
        fdesde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fdesdeActionPerformed(evt);
            }
        });

        rbTodos.setText("Todos");
        rbTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbTodosActionPerformed(evt);
            }
        });

        rbMenor10.setText("Menor a 10");
        rbMenor10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMenor10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tdesde)
                            .addComponent(thasta, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fhasta, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                            .addComponent(fdesde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbTodos)
                            .addComponent(rbMenor10))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbTodos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMenor10)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fdesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(thasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fhasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
        );

        jPanel3.setBackground(new java.awt.Color(173, 216, 230));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Seleccione opcion", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jr_fecha.setBackground(new java.awt.Color(173, 216, 230));
        jr_fecha.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jr_fecha.setText("Registro por Fecha");
        jr_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jr_fechaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jr_fecha)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jr_fecha)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(173, 216, 230));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Reportes", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        radioInventario.setBackground(new java.awt.Color(173, 216, 230));
        radioInventario.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radioInventario.setText("Reporte Inventario");
        radioInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioInventarioActionPerformed(evt);
            }
        });

        radioVentas.setBackground(new java.awt.Color(173, 216, 230));
        radioVentas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radioVentas.setText("Reporte Ventas");
        radioVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioVentasActionPerformed(evt);
            }
        });

        radioCajas.setBackground(new java.awt.Color(173, 216, 230));
        radioCajas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radioCajas.setText("Reporte Movimiento Cajas");
        radioCajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCajasActionPerformed(evt);
            }
        });

        radioCompras.setBackground(new java.awt.Color(173, 216, 230));
        radioCompras.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        radioCompras.setText("Reporte Compras");
        radioCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioComprasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radioCajas, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(radioInventario, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                        .addComponent(radioVentas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(radioInventario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCajas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(116, 116, 116)
                        .addComponent(jBgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(22, 22, 22)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(24, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBgenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioVentasActionPerformed
        // TODO add your handling code here:
        if (radioVentas.isSelected()) {
            bandera = "Ventas";
            radioInventario.setSelected(false);
            radioCajas.setSelected(false);
        }
    }//GEN-LAST:event_radioVentasActionPerformed

    private void jBgenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBgenerarActionPerformed

        if (bandera == "Inventario") {
            if (rbTodos.isSelected()) {
                generarInformeStock();
                dispose();
            } else if (rbMenor10.isSelected()) {
                generarInformeStockMenor10();
                dispose();
            }
        }
        if (bandera == "Ventas" && fechas == "SI") {
            generarInformeVentas();
            dispose();
        }
        if (bandera == "Cajas" && fechas == "SI") {

            generarInformeCajas();
            dispose();
        }
        if (bandera == "Compras" && fechas == "SI") {
            generarInformeCompras();
            dispose();
        }
    }//GEN-LAST:event_jBgenerarActionPerformed

    private void radioInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioInventarioActionPerformed
        // TODO add your handling code here:
        if (radioInventario.isSelected()) {
            this.bandera = "Inventario";
            radioVentas.setSelected(false);
            radioCajas.setSelected(false);
            radioCompras.setSelected(false);
            jr_fecha.setEnabled(true);
        }

    }//GEN-LAST:event_radioInventarioActionPerformed

    private void tdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdesdeActionPerformed
        if (tdesde.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío");
            this.tdesde.setEnabled(true);
            this.tdesde.requestFocus();
        } else {
            this.fdesde.setEnabled(true);
            this.fdesde.requestFocus();
    }//GEN-LAST:event_tdesdeActionPerformed
    }
    private void thastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thastaActionPerformed
        if (thasta.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío");
            this.thasta.setEnabled(true);
            this.thasta.requestFocus();
        } else {
            this.fhasta.setEnabled(true);
            this.fhasta.requestFocus();
        }

    }//GEN-LAST:event_thastaActionPerformed

    private void jr_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jr_fechaActionPerformed
        fechas = "SI";
        tdesde.setText("");
        thasta.setText("");
        tdesde.setEnabled(true);
        thasta.setEnabled(true);
        tdesde.requestFocus();
        //    jr_todos.setSelected(false);
    }//GEN-LAST:event_jr_fechaActionPerformed

    private void radioCajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCajasActionPerformed
        // TODO add your handling code here:
        if (radioCajas.isSelected()) {
            bandera = "Cajas";
            radioInventario.setSelected(false);
            radioVentas.setSelected(false);
            radioCompras.setSelected(false);
            jr_fecha.setEnabled(true);
        }
    }//GEN-LAST:event_radioCajasActionPerformed

    private void fhastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fhastaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fhastaActionPerformed

    private void fdesdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fdesdeActionPerformed
        // TODO add your handling code here:
        if (fdesde.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "El campo de texto está vacío");
            this.fdesde.setEnabled(true);
            this.fdesde.requestFocus();
        } else {
            this.thasta.setEnabled(true);
            this.thasta.requestFocus();
        }
    }//GEN-LAST:event_fdesdeActionPerformed

    private void rbTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTodosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbTodosActionPerformed

    private void rbMenor10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMenor10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbMenor10ActionPerformed

    private void radioComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioComprasActionPerformed
        // TODO add your handling code here:
        if (radioCompras.isSelected()) {
            bandera = "Compras";
            radioInventario.setSelected(false);
            radioVentas.setSelected(false);
            radioCajas.setSelected(false);
            jr_fecha.setEnabled(true);
        }
    }//GEN-LAST:event_radioComprasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReporteInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReporteInventario().setVisible(true);
            }
        });
    }
    public String bandera = "";
    public String fechas = "";
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JFormattedTextField fdesde;
    private javax.swing.JFormattedTextField fhasta;
    private javax.swing.JButton jBgenerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jr_fecha;
    private javax.swing.JRadioButton radioCajas;
    private javax.swing.JRadioButton radioCompras;
    private javax.swing.JRadioButton radioInventario;
    private javax.swing.JRadioButton radioVentas;
    private javax.swing.JRadioButton rbMenor10;
    private javax.swing.JRadioButton rbTodos;
    private javax.swing.JFormattedTextField tdesde;
    private javax.swing.JFormattedTextField thasta;
    // End of variables declaration//GEN-END:variables

    private void generarInformeStock() {
        try {
            ver_conex con = new ver_conex();

            JasperReport reporte = null;

            String path = "\\reportes2\\Inventario.jasper";

            reporte = (JasperReport) JRLoader.loadObjectFromFile(System.getProperty("user.dir") + path);

            JasperPrint jp = JasperFillManager.fillReport(reporte, null, con.conexion);

            JasperViewer jv = new JasperViewer(jp, false);

            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(ReporteInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarInformeStockMenor10() {
        try {
            ver_conex con = new ver_conex();

            JasperReport reporte = null;

            String path = "\\reportes2\\Inventario2.jasper";

            reporte = (JasperReport) JRLoader.loadObjectFromFile(System.getProperty("user.dir") + path);

            JasperPrint jp = JasperFillManager.fillReport(reporte, null, con.conexion);

            JasperViewer jv = new JasperViewer(jp, false);

            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(ReporteInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarInformeVentas() {
        try {
            ver_conex con = new ver_conex();

            JasperReport reporte = null;

            String path = "\\reportes2\\ReporteVentas.jasper";

            Map parametro = new HashMap();
            parametro.put("fecha_inicio", tdesde.getText());
            parametro.put("hora_inicio", fdesde.getText());

            parametro.put("fecha_fin", thasta.getText());
            parametro.put("hora_fin", fhasta.getText());

            reporte = (JasperReport) JRLoader.loadObjectFromFile(System.getProperty("user.dir") + path);

            JasperPrint jp = JasperFillManager.fillReport(reporte, parametro, con.conexion);

            JasperViewer jv = new JasperViewer(jp, false);

            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(ReporteInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarInformeCajas() {
        try {
            ver_conex con = new ver_conex();

            JasperReport reporte = null;

            String path = "\\reportes2\\ReporteMovCajas.jasper";

            Map parametro = new HashMap();
            parametro.put("fecha_inicio", tdesde.getText());
            parametro.put("hora_inicio", fdesde.getText());

            parametro.put("fecha_fin", thasta.getText());
            parametro.put("hora_fin", fhasta.getText());

            reporte = (JasperReport) JRLoader.loadObjectFromFile(System.getProperty("user.dir") + path);

            JasperPrint jp = JasperFillManager.fillReport(reporte, parametro, con.conexion);

            JasperViewer jv = new JasperViewer(jp, false);

            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(ReporteInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void generarInformeCompras() {
        try {
            ver_conex con = new ver_conex();

            JasperReport reporte = null;

            String path = "\\reportes2\\ReporteCompras.jasper";

            Map parametro = new HashMap();
            parametro.put("fecha_inicio", tdesde.getText());
            parametro.put("hora_inicio", fdesde.getText());

            parametro.put("fecha_fin", thasta.getText());
            parametro.put("hora_fin", fhasta.getText());

            reporte = (JasperReport) JRLoader.loadObjectFromFile(System.getProperty("user.dir") + path);

            JasperPrint jp = JasperFillManager.fillReport(reporte, parametro, con.conexion);

            JasperViewer jv = new JasperViewer(jp, false);

            jv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            jv.setVisible(true);

        } catch (JRException ex) {
            Logger.getLogger(ReporteInventario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
