
package formularios;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import programas.ver_conex;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.SQLException;
//import java.util.logging.Level;
//import java.util.logging.Logger;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Eduardo
 */
public class vehiculos extends javax.swing.JFrame {
ver_conex conn = new ver_conex();
 javax.swing.table.DefaultTableModel cursor;
  //javax.swing.table.DefaultTableModel cursor;
     
    private Object bandera;
    /**
     * Creates new form vehiculos
     */
    public vehiculos() {
        initComponents();
         cursor = (javax.swing.table.DefaultTableModel)grilla.getModel();
        des_text();
         this.setLocationRelativeTo(null);
         hab_botones();
          txtchapa.setEnabled(false);
          beditar.setEnabled(false);
        txtcodigo.setEnabled(false);
         cargar_grilla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtchasis = new javax.swing.JTextField();
        lruc = new javax.swing.JLabel();
        beditar = new javax.swing.JButton();
        lcodigo = new javax.swing.JLabel();
        bcancelar = new javax.swing.JButton();
        bgrabar = new javax.swing.JButton();
        marcod = new javax.swing.JTextField();
        bsalir = new javax.swing.JButton();
        txtvehinumero = new javax.swing.JTextField();
        txtcodigo = new javax.swing.JTextField();
        bnuevo = new javax.swing.JButton();
        txtchapa = new javax.swing.JTextField();
        mardesc = new javax.swing.JTextField();
        ltelefono1 = new javax.swing.JLabel();
        ltelefono2 = new javax.swing.JLabel();
        lnombre = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bborrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grilla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtchasis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtchasisKeyTyped(evt);
            }
        });

        lruc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lruc.setText("Motor Chasis:");

        beditar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        beditar.setText("Editar");
        beditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beditarActionPerformed(evt);
            }
        });

        lcodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lcodigo.setText("Codigo :");

        bcancelar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bcancelar.setText("Cancelar");
        bcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bcancelarActionPerformed(evt);
            }
        });

        bgrabar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bgrabar.setText("Grabar");
        bgrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bgrabarActionPerformed(evt);
            }
        });

        marcod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcodActionPerformed(evt);
            }
        });
        marcod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                marcodKeyPressed(evt);
            }
        });

        bsalir.setBackground(new java.awt.Color(255, 255, 255));
        bsalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bsalir.setText("Salir");
        bsalir.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalirActionPerformed(evt);
            }
        });

        txtvehinumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvehinumeroKeyTyped(evt);
            }
        });

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        bnuevo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bnuevo.setText("Nuevo");
        bnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnuevoActionPerformed(evt);
            }
        });

        txtchapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtchapaActionPerformed(evt);
            }
        });

        mardesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mardescActionPerformed(evt);
            }
        });

        ltelefono1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ltelefono1.setText("Chapa Numero:");

        ltelefono2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ltelefono2.setText("Marca:");

        lnombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lnombre.setText("Numero de Vehiculo:");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Vehiculos");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        bborrar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        bborrar.setText("Borrar");
        bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bborrarActionPerformed(evt);
            }
        });

        grilla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Marca Codigo", "Marca Descripcion", "Chapa", "Chasis", "Nro Vehiculo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(grilla);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ltelefono1)
                                .addGap(18, 18, 18)
                                .addComponent(txtchapa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ltelefono2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(marcod, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mardesc, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lcodigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lruc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtchasis, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lnombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtvehinumero, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(beditar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bsalir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bnuevo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bcancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bgrabar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bborrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bnuevo)
                        .addGap(13, 13, 13)
                        .addComponent(beditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bborrar)
                        .addGap(15, 15, 15)
                        .addComponent(bgrabar)
                        .addGap(18, 18, 18)
                        .addComponent(bcancelar)
                        .addGap(26, 26, 26)
                        .addComponent(bsalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lcodigo)
                            .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltelefono2)
                            .addComponent(mardesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(marcod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ltelefono1)
                            .addComponent(txtchapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtchasis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lruc))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lnombre)
                            .addComponent(txtvehinumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtchasisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtchasisKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtchasisKeyTyped

    private void beditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beditarActionPerformed
        // TODO add your handling code here:
        bandera = "editar";
        des_botones();
        txtcodigo.setEnabled(true);
        txtcodigo.requestFocus();
    }//GEN-LAST:event_beditarActionPerformed

    private void bcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bcancelarActionPerformed
        hab_botones();
        des_text();
        borrar_text();
    }//GEN-LAST:event_bcancelarActionPerformed

    private void bgrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bgrabarActionPerformed
        // TODO add your handling code here:
        grabar();
        borrar_text();
        cargar_grilla();
    }//GEN-LAST:event_bgrabarActionPerformed

    private void bsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalirActionPerformed
        // TODO add your handling code here:
        salir();
    }//GEN-LAST:event_bsalirActionPerformed

    private void txtvehinumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvehinumeroKeyTyped
        // TODO add your handling code here:
//        int letra = (int) evt.getKeyChar();
//        if (letra > 47 && letra < 58) {
//            evt.setKeyChar((char) KeyEvent.VK_CLEAR);
//            getToolkit().beep();///el sonido del error
//            evt.consume();////mantiene el pulsor al presionar espacio
//            JOptionPane.showMessageDialog(null,"No puede Ingresar Numeros");
//            txtvehinumero.requestFocus();
//        }
//
//        if (letra == 10) // enter
//        {
//            //transfiere el foco si presionas enter
//            bgrabar.setEnabled(true);
//            bgrabar.requestFocus();
//
//        }
    }//GEN-LAST:event_txtvehinumeroKeyTyped

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_txtcodigoActionPerformed

    private void bnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnuevoActionPerformed
        bandera = "agregar";
        hab_text();
        des_botones();
        txtcodigo.requestFocus();
        gencod();
        //txtruc.setEnabled(true);
        marcod.requestFocus();
        txtcodigo.setEnabled(false);
    }//GEN-LAST:event_bnuevoActionPerformed

    private void txtchapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtchapaActionPerformed
        // TODO add your handling code here:
        comparar();
    }//GEN-LAST:event_txtchapaActionPerformed

    private void mardescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mardescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mardescActionPerformed

    private void bborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bborrarActionPerformed
        // TODO) add your handling code here:
        bandera = "borrar";
        des_botones();
        txtcodigo.setEnabled(true);
        txtcodigo.requestFocus();
    }//GEN-LAST:event_bborrarActionPerformed

    private void marcodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcodKeyPressed
        // TODO add your handling code here:
        if (marcod.getText().equals("") && evt.getKeyChar() == KeyEvent.VK_ENTER)//no trae nada
        {
            JTextField[] tfParam = new JTextField[2];
            tfParam[0] = this.marcod;
            tfParam[1] = this.mardesc;

            VentanaBuscar buscador = new VentanaBuscar("select ciu_cod,ciu_descri from ciudad where ciu_descri like  ", new String[]{"CODIGO ciudad", "NOMBRE ciudad"}, 2, tfParam);
            buscador.setTitle("Buscar ciudad");
            buscador.setVisible(true);
        }
        //// TODO add your handling code here:
    }//GEN-LAST:event_marcodKeyPressed

    private void marcodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcodActionPerformed
        // TODO add your handling code here:
        buscarmarcas();
    }//GEN-LAST:event_marcodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vehiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bborrar;
    private javax.swing.JButton bcancelar;
    private javax.swing.JButton beditar;
    private javax.swing.JButton bgrabar;
    private javax.swing.JButton bnuevo;
    private javax.swing.JButton bsalir;
    private javax.swing.JTable grilla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lcodigo;
    private javax.swing.JLabel lnombre;
    private javax.swing.JLabel lruc;
    private javax.swing.JLabel ltelefono1;
    private javax.swing.JLabel ltelefono2;
    private javax.swing.JTextField marcod;
    private javax.swing.JTextField mardesc;
    private javax.swing.JTextField txtchapa;
    private javax.swing.JTextField txtchasis;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtvehinumero;
    // End of variables declaration//GEN-END:variables
private void buscarmarcas()
    {
        try {
             ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT * FROM marcas WHERE mar_cod="+marcod.getText());
            boolean encontro = conn.resultado.next();

            if(encontro == true)
            {
                mardesc.setText(conn.resultado.getString("mar_desc"));
            }
            else // no encontro
            {
              JOptionPane.showMessageDialog(null, "No existe un registro con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(marcas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void hab_text() // sirve para habilitar los textos
	 {

	txtcodigo.setEnabled (false);
	//txtnombre.setEnabled (true);
	txtvehinumero.setEnabled (true);
	//txtdireccion.setEnabled (true);
	//txttelefono.setEnabled (true);
        txtchasis.setEnabled(true);
        txtchapa.setEnabled(true);
         marcod.setEnabled(true);
        // txtemail.setEnabled(true);
         mardesc.setEnabled(false);
	}

	 private void des_text()	// metodo para deshabilitar los textos
     {
        txtcodigo.setEnabled (false);
	//txtnombre.setEnabled (false);
	txtvehinumero.setEnabled (false);
	//txtdireccion.setEnabled (false);
	//txttelefono.setEnabled (false);
    txtchasis.setEnabled(false);
    txtchapa.setEnabled(false);
    marcod.setEnabled(false);
   // txtemail.setEnabled(false);
    mardesc.setEnabled(false);
     }	
	
	 private void borrar_text()	//metodo para dejar en blanco el texto
     {
         txtcodigo.setText("");	
         //txtnombre.setText("");
	 txtvehinumero.setText("");
	// txtdireccion.setText("");
	 //txttelefono.setText("");
         txtchasis.setText("");
         txtchapa.setText("");
         marcod.setText("");
         mardesc.setText("");
     }	

	
	  private void des_botones() //metodo para deshabilitar botones	
     {
         bnuevo.setEnabled(false);
	 bborrar.setEnabled(false);
         beditar.setEnabled(false);
         bgrabar.setEnabled(true);
         bsalir.setEnabled(false);
	 bcancelar.setEnabled(true);
     }	

     private void hab_botones()	// metodo para hab botones
     {
         bnuevo.setEnabled(true);
	 bborrar.setEnabled(true);
         beditar.setEnabled(true);
         bgrabar.setEnabled(false);
         bsalir.setEnabled(true);
	 bcancelar.setEnabled(false);
     }

 private void gencod()
    {
        try {
            //       Main.inicio = "no";
                   ver_conex conn = new ver_conex();
                   conn.sentencia = conn.conexion.createStatement();
                   conn.resultado = conn.sentencia.executeQuery("SELECT IFNULL(MAX(vehi_cod),0)+ 1 AS xxx FROM vehiculo");
                   conn.resultado.next();
                  this.txtcodigo.setText(conn.resultado.getString("xxx"));
        } catch (SQLException ex) {
            Logger.getLogger(vehiculos.class.getName()).log(Level.SEVERE, null, ex);
     //   } catch (SQLException ex)
        {
            Logger.getLogger(vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
 }
 private void grabar()
    {
        try {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();

            if(bandera.equals("agregar"))
             {
                 gencod();// sirve para que no se dupliquen los codigos y no de error cuando se trabaja en redes
               conn.sentencia.executeUpdate("INSERT INTO vehiculo(vehi_cod,mar_cod,chapa,chasis,estado,nro_vehi)values("+txtcodigo.getText()+","+marcod.getText()+",'"+txtchapa.getText()+"','"+txtchasis.getText()+"','ACTIVO','"+txtvehinumero.getText()+"')");
              cargar_grilla();
              this.bcancelar.doClick();
             }

            if(bandera.equals("editar"))
             {
             
                 conn.sentencia.executeUpdate
                         ("UPDATE vehiculo SET mar_cod='"+marcod.getText()+"',chapa='"+txtchapa.getText()+"',chasis='"+txtchasis.getText()+"',"
                         + "nro_vehi='"+txtvehinumero.getText()+"',"
                         + " WHERE cli_cod ="+txtcodigo.getText());
               cargar_grilla();
             }
             JOptionPane.showMessageDialog(null, "REGISTRO GRABADO","CONFIRMACION",JOptionPane.INFORMATION_MESSAGE);
          this.bcancelar.doClick();
        } catch (SQLException ex) {
            Logger.getLogger(clientes2.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
        private void buscar()
                
    {
        try {
           // Main.inicio = "no";
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery
       ("SELECT * FROM vehiculo WHERE vehi_cod = "+txtcodigo.getText());
            boolean encontro = conn.resultado.next();

            if(encontro == true)
            {
              //  txtnombre.setText(conn.resultado.getString("cli_nom"));
                txtvehinumero.setText(conn.resultado.getString("nro_vehi"));
               // txtdireccion.setText(conn.resultado.getString("cli_dir"));
               // txttelefono.setText(conn.resultado.getString("cli_tel"));
                txtchasis.setText(conn.resultado.getString("chasis"));
                marcod.setText(conn.resultado.getString("mar_cod"));
               // txtemail.setText(conn.resultado.getString("cli_email"));
                txtchapa.setText(conn.resultado.getString("chapa"));

                if(bandera.equals("borrar"))
                {
                   int mensaje = JOptionPane.showConfirmDialog(this,"Deseas Borrar-->"+txtvehinumero.getText(),"Confirmar",JOptionPane.YES_NO_OPTION);
                     if(mensaje == JOptionPane.YES_OPTION)//si quiere borrar
                     {
                           conn.sentencia = conn.conexion.createStatement();
                           conn.sentencia.executeUpdate("UPDATE vehiculo SET vehi_est ='Borrado' Where vehi_cod= "+txtcodigo.getText()+"");
                          JOptionPane.showMessageDialog(null, "El registro ha sido borrado satisfactoriamente.", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                      cargar_grilla();
                     
                     }
                     else
                     {
                        JOptionPane.showMessageDialog(null, "Operacion Cancelada", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                     }
                     this.bcancelar.doClick();




                }//fin de borrar


                 if(bandera.equals("editar"))
                 {
                  //   txtnombre.setEnabled(true);
                    // txtruc.requestFocus();
                     txtvehinumero.setEnabled(true);
                   //  txttelefono.setEnabled(true);
                     txtchasis.setEnabled(true);
                    // txtdireccion.setEnabled(true);
                  //    txtruc.setText(conn.resultado.getString("cli_ruc"));
                marcod.setEnabled(true);
                marcod.requestFocus();
              //  txtemail.setEnabled(encontro);
                txtchapa.setEnabled(true);
                 }//fin de editar

       // catch (SQLException ex) {
         //   Logger.getLogger(grupos.class.getName()).log(Level.SEVERE, null, ex);
        //}            else
            } else // no encontro
            {
              JOptionPane.showMessageDialog(null, "No existe un registro con este codigo!", "Atencion", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException ex) {
            Logger.getLogger(vehiculos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
private void salir (){
     int respuesta = JOptionPane.showConfirmDialog
         (this,"DESEA SALIR","CONFIRMAR",JOptionPane.YES_NO_OPTION);
       if(respuesta == JOptionPane.YES_OPTION)
       {
	   dispose();

       }
 
}
// public void genreporte() //throws JRException, Exception
//    {
//        try //throws JRException, Exception
//        {
//            ver_conex conn = new ver_conex();    
//            conn.sentencia = conn.conexion.createStatement();
//            conn.resultado = conn.sentencia.executeQuery("SELECT * FROM cliente"); //OJO LE PASO LA SENTENCIA
//            JRResultSetDataSource jrRS = new JRResultSetDataSource(conn.resultado);
//
//            HashMap parameters = new HashMap();
//            URL urlMaestro = getClass().getClassLoader().getResource("reportes/clientes.jasper");
//
//            // Cargamos el reporte
//            JasperReport masterReport = null;
//            masterReport = (JasperReport) JRLoader.loadObject(urlMaestro);
//            JasperPrint masterPrint = null;
//            masterPrint = JasperFillManager.fillReport(masterReport, parameters, jrRS);
//            JasperViewer ventana = new JasperViewer(masterPrint, false);
//            ventana.setTitle("Vista Previa");
//            ventana.setVisible(true);
//
//        } catch (JRException ex) {
//            Logger.getLogger(clientes1.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(clientes1.class.getName()).log(Level.SEVERE, null, ex);
//        }
//    }   
 
  private void cargar_grilla()
  {
      try
      {
           for (int i = grilla.getRowCount()-1; i>=0; i--)
            {
                cursor.removeRow(i);
            }
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery("SELECT * FROM vehiculo,marcas WHERE vehiculo.mar_cod=marcas.mar_cod");
           
            while(conn.resultado.next())
            {
                Object[] datos = {conn.resultado.getString("vehi_cod"),
                                  conn.resultado.getString("mar_cod"),
                                  conn.resultado.getString("mar_desc"),
                                  conn.resultado.getString("chapa"),
                                  conn.resultado.getString("chasis"),
                                  conn.resultado.getString("nro_vehi"),
                                  conn.resultado.getString("estado"),
                };
                cursor.addRow(datos);  
            }

        } catch (SQLException ex) {
            Logger.getLogger(clientes2.class.getName()).log(Level.SEVERE, null, ex);
        }
  }
  private void comparar()
     {
            String texto;
            String ValidarDuplicados;
            texto = txtchapa.getText().trim();
            texto.toUpperCase();
            ValidarDuplicados="SELECT cli_ci as descripcion FROM cliente WHERE cli_ci='"+texto+"'";
            try
            {
            ver_conex conn = new ver_conex();
            conn.sentencia = conn.conexion.createStatement();
            conn.resultado = conn.sentencia.executeQuery(ValidarDuplicados);
                int Bandera = 0;
                
            if (conn.resultado.next() && Bandera != 2) /*Esta validacion se aplica cuand*/
            {
              JOptionPane.showMessageDialog(null, "El registro que intenta ingresar ya existe", "Atencion", JOptionPane.ERROR_MESSAGE);  
            txtchapa.setEnabled(true);
            bgrabar.setEnabled(false);
            txtchapa.requestFocus();
            }
                    else{
                    bgrabar.setEnabled(true);
                    bgrabar.requestFocus();
            }
        }
        catch(SQLException SqlError)
        {
        JOptionPane.showMessageDialog(null,"No se ejecuto la consulta verifique parametros. "+SqlError);
        }
     }
}

