/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package formularios;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import org.jvnet.substance.SubstanceLookAndFeel;
import org.jvnet.substance.button.StandardButtonShaper;
import programas.ver_conex;

/**
 *
 * @author claudia
 */
public class ventanabuscador extends javax.swing.JFrame {

   int col;
    String[] nom;
    ArrayList<String[]> val = new ArrayList<String[]>();
    String query;
    String des;
    int cod;
    Object[] tfParam;
    
    
    public ventanabuscador (String consulta_sql,String[] nombre_columnas,int cantidad_columnas,Object[] objetos_pa_devolver_resultado) {
        this.query  =consulta_sql;
        this.nom = nombre_columnas;
        this.col = cantidad_columnas;
        this.tfParam = objetos_pa_devolver_resultado;
                
        initComponents();
         setAlwaysOnTop( true );
        this.setLocationRelativeTo(null);
       
        this.jbtnBuscar.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
        this.jbtnSeleccionar.putClientProperty(SubstanceLookAndFeel.BUTTON_SHAPER_PROPERTY, new StandardButtonShaper());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnlBuscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtfValorBusqueda = new javax.swing.JTextField();
        jbtnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblDetalleBusqueda = new javax.swing.JTable();
        jbtnSeleccionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnlBuscar.setBackground(new java.awt.Color(255, 255, 255));
        jpnlBuscar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/arqueo.png"))); // NOI18N
        jLabel1.setText("Descripcion:");

        jtxtfValorBusqueda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtfValorBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfValorBusquedaActionPerformed(evt);
            }
        });

        jbtnBuscar.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jbtnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/buscar (2).PNG"))); // NOI18N
        jbtnBuscar.setText("BUSCAR");
        jbtnBuscar.setToolTipText("presione este boton para traer los datos completos sin necesidad de buscar por descripcion");
        jbtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnlBuscarLayout = new javax.swing.GroupLayout(jpnlBuscar);
        jpnlBuscar.setLayout(jpnlBuscarLayout);
        jpnlBuscarLayout.setHorizontalGroup(
            jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBuscarLayout.createSequentialGroup()
                .addGap(325, 325, 325)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jtxtfValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnlBuscarLayout.setVerticalGroup(
            jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlBuscarLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jpnlBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtfValorBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/Imagen4.png"))); // NOI18N
        jLabel2.setLabelFor(jScrollPane1);
        jLabel2.setToolTipText("Seleccione en la grilla el registro que desea cargar y precione la tecla \"ENTER\" para cargar los datos");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jtblDetalleBusqueda.setModel(new ModeloTabla(col, nom, val));
        jtblDetalleBusqueda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblDetalleBusquedaMouseClicked(evt);
            }
        });
        jtblDetalleBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtblDetalleBusquedaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtblDetalleBusqueda);

        jbtnSeleccionar.setFont(new java.awt.Font("Lucida Bright", 1, 14)); // NOI18N
        jbtnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/grafico/SALIR.png"))); // NOI18N
        jbtnSeleccionar.setText("Salir");
        jbtnSeleccionar.setToolTipText("presione salir si desea salir del buscador");
        jbtnSeleccionar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSeleccionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 759, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, 0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addComponent(jbtnSeleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnlBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnlBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBuscarActionPerformed
        // TODO add your handling code here:
        
        try {
          // conexion con = new conexion();
            ver_conex conn = new ver_conex();
            // ResultSet exito = con.dameLista(query+" upper('%"+this.jtxtfValorBusqueda.getText().toString()+"%')");
          boolean exito = conn.ejecurarConsulta(query+" upper('%"+this.jtxtfValorBusqueda.getText().toString()+"%')");
            val = new ArrayList<String[]>();
           if(exito){
                while (conn.resultado.next()) {
                    String[] aux = new String[col];
                    for (int i = 0; i < aux.length; i++) {
                        aux[i] = String.valueOf(conn.resultado.getObject(i+1));
                        
                    }
                    val.add(aux);                  
                }
            }
            jtblDetalleBusqueda.setModel(new ModeloTabla(col, nom, val));
        } catch (SQLException ex) {
            ex.printStackTrace();
        }

        
    }//GEN-LAST:event_jbtnBuscarActionPerformed

    private void jbtnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSeleccionarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        

    }//GEN-LAST:event_jbtnSeleccionarActionPerformed

    private void jtblDetalleBusquedaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblDetalleBusquedaMouseClicked
        // TODO add your handling code here:
        for (int i = 0; i < tfParam.length; i++) {
        if(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i) != null) {
            if ( tfParam[i] instanceof JTextField ) {
                 //System.out.println(((JTextField)tfParam[i]).getName());
                ((JTextField)tfParam[i]).setText(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
            }
            else if(tfParam[i] instanceof JComboBox){
                int indice =Integer.parseInt(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
                //System.out.print(indice);
                ((JComboBox)tfParam[i]).setSelectedIndex(indice);
                    //DropDown itemcbo = (DropDown)((JComboBox)tfParam[i]).getItemAt(indice);
                    //System.out.println(itemcbo.getCodigo());
            }
//            else if(tfParam[i] instanceof JTable) {
//                int indice =Integer.parseInt(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
//                //System.out.print(indice);
//                ((JTable)tfParam[i]).setSelectionMode(indice);
//            }
            
        }
            //tfParam[i].setText(jtblDetalleBusqueda.getValueAt(jtblDetalleBusqueda.getSelectedRow(),i).toString());
    }//Cierre del for
         
        
    }//GEN-LAST:event_jtblDetalleBusquedaMouseClicked

    private void jtxtfValorBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfValorBusquedaActionPerformed
        // TODO add your handling code here:
                this.jbtnBuscar.requestFocus();
    }//GEN-LAST:event_jtxtfValorBusquedaActionPerformed

    private void jtblDetalleBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtblDetalleBusquedaKeyPressed
        // TODO add your handling code here:
         this.dispose();
    }//GEN-LAST:event_jtblDetalleBusquedaKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ventanabuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ventanabuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ventanabuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ventanabuscador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
              //  new ventanabuscador().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnBuscar;
    private javax.swing.JButton jbtnSeleccionar;
    private javax.swing.JPanel jpnlBuscar;
    private javax.swing.JTable jtblDetalleBusqueda;
    private javax.swing.JTextField jtxtfValorBusqueda;
    // End of variables declaration//GEN-END:variables
}
